changelog.txt, footer.php, inc/compatibility/class-ast-bb-ultimate-addon.php
Moved hook ast_body_bottom at the top of the wp_footer hook.
=> Renamed the uabb theme compatibility functions to not include redundant prefix

inc/class-ast-after-setup-theme.php, inc/compatibility/class-ast-woocommerce.php, style.css
Updated the Theme-Support and Theme URI
=> Update theme support/uri

style.css
Screenshot images license added
=> Screenshot license added

inc/customizer/sections/layout/header.php
Sanitize text field added for menu label.
=> Sanitize text field added

changelog.txt, functions.php, inc/blog/blog-config.php, inc/class-astra-after-setup-theme.php, inc/class-astra-dynamic-css.php, inc/core/class-theme-strings.php, inc/core/common-functions.php, inc/extras.php, languages/astra.pot, package.json, style.css
v1.0.5.1
Fixed: Use `&hellip;` instead of `...`
Fixed: Use sanitize_html_class to sanitize HTML class
Fixed: Remove comment-list from add_theme_support( 'html5' )
Fixed: Escaping implemented for Dynamic CSS
Search result page escaping issue.
=> Merge V1.0.5.1

inc/customizer/register-panels-and-sections.php, inc/customizer/sections/advanced/buttons.php, inc/customizer/sections/typography/content.php
Advanced Panel String Updated,
Heading section String updated
=> Advanced string update

inc/customizer/sections/colors-background/body.php
Customizer option renamed to Theme Color / Link Color.
=> Rename theme customizer option name

inc/customizer/register-panels-and-sections.php
Customizer options order updated.
=> Customizer option order updated

inc/core/class-astra-enqueue-scripts.php
=> Removed dyanamic css filter

changelog.txt
=> Changelog updated.

inc/customizer/sections/typography/archive.php
Archive Summary typography option order changed.
=> Archive Summary typography option order changed

inc/customizer/sections/buttons/buttons.php
Button Color option rename to Button Text Color.
=> Button customizer option renamed

inc/customizer/custom-controls/typography/class-astra-control-typography.php, inc/customizer/custom-controls/typography/typography.js, inc/customizer/sections/typography/body.php
Default Body Font Family, Font Weight & Text Transform updated from 'Inherit' to  'Default'.
=> Body typography

changelog.txt, functions.php, languages/astra.pot, package.json, style.css
Removed accessibility-ready until the final review is done.
=> Removed accessibility-ready tag

inc/core/common-functions.php, inc/extras.php, template-parts/blog/blog-layout.php, template-parts/content-page.php, template-parts/single/single-layout.php
Implemented 3 filters for toolset compatibility as follows:
1. 'astra_pagination_enabled' 
- Data Type: bool,
- Default: true,
- Description: Filter to enable or disable paginations from blog/archive Page.
2. 'astra_the_title_enabled' 
- Data Type: bool,
- Default: true,
- Description: Filter to enable or disable title from site.
3. 'astra_featured_image_enabled' 
- Data Type: bool,
- Default: true,
- Description: Filter to enable or disable featured images from site.
=> Toolset compatibile filters implemented.

inc/blog/blog-config.php, inc/blog/single-blog.php, inc/class-astra-dynamic-css.php, inc/compatibility/class-astra-beaver-builder.php, inc/compatibility/class-astra-beaver-themer.php, inc/core/class-astra-theme-options.php, inc/core/class-astra-theme-update.php, inc/core/class-theme-strings.php, inc/customizer/sections/layout/container.php, inc/customizer/sections/layout/footer.php, inc/customizer/sections/layout/sidebar.php, inc/extras.php, inc/metabox/class-astra-meta-boxes.php
https://trello.com/c/q0b86H7p/626-toolset-filter
https://trello.com/c/nD9Ho4GU/625-footer-widgets-should-be-disabled-by-default
https://trello.com/c/ijwojH1I/624-change-default-setting-for-content-layout-and-change-content-layout-string-to-default-layout
https://trello.com/c/PZoDwdJd/623-change-strings-form-page-builder-to-full-width
https://trello.com/c/Omt1YZDL/622-the-default-footer-bar-border-should-be-1px-and-color-should-be-7a7a7a
https://trello.com/c/9YtvQ9eq/618-implement-dynamic-strings
https://trello.com/c/ZDNciBRf/617-do-not-call-function-directly-use-filter-for-pagination
=> Astra Improvements, fixes and updated strings

inc/customizer/class-astra-fonts.php, inc/customizer/custom-controls/typography/class-astra-control-typography.php, inc/customizer/custom-controls/typography/typography.js
Add Filter/Action to support custom font support.
=> Custom fonts support

inc/customizer/class-astra-fonts-data.php, inc/customizer/custom-controls/typography/class-astra-control-typography.php, inc/customizer/custom-controls/typography/typography.js
Add Filter to extend the font list in customizer.
=> Typekit Custom Fonts Support

inc/extras.php
Append current theme version class to body
=> Add current verion of astra theme into body class

functions.php, style.css
- Fixed: Title is not working for anspress questions shortcode.
=> Version bump v1.0.18.1

changelog.txt, inc/class-astra-dynamic-css.php, inc/core/class-astra-admin-settings.php
- Fixed: Title is not working for anspress questions shortcode.
- Fixed: Accessibility, focus on navigation link, color not working as on hover
- Fixed: Display correct page title When on Astra Settings Page.
=> Quick fixes

inc/core/class-astra-admin-settings.php, inc/extras.php
Example usage - 
```
function your_prefix_astra_color_pallete ( $color_pallets ) {
$color_pallets = array(
'#000000',
'#ffffff',
'#dd3333',
'#dd9933',
'#eeee22',
'#81d742',
'#1e73be',
'#8224e3',
);
return $color_pallets;
}
apply_filters( 'astra_color_palletes', 'your_prefix_astra_color_pallete' );
```
=> Astra color pallets filter added

changelog.txt, inc/core/view-general.php
v1.0.23
Improvement: Added filter to support white-label for the theme name on theme's welcome page.
=> White label filter for welcome page details

inc/customizer/class-astra-customizer.php
Filter moved to outside of logo generate function.
=> Logo image size filter call changed

changelog.txt, functions.php, package.json, style.css
- Improvement: Save the current theme version in the database so that it can be used for data processing on theme upgrades.
=> Version v1.0.24

changelog.txt
Elementor Nav Menu fixed changelog added...
=> Changelog update for Navmenu fix

inc/customizer/custom-controls/radio-image/radio-image.css, inc/customizer/custom-controls/radio-image/radio-image.scss
Issue : Radio images slightly jump when we select any one of them.
Fix : Updated css of radio image control.
=> Fixed radio-image control issue

inc/blog/blog-config.php, inc/extras.php
Read more text and class filters added
=> Read more text and class filters added

inc/extras.php
Issue : Archive page features image not showing
Fixed : Updated condition for archive page
=> Blog featured img

inc/extras.php
Load the full size of the logo when in customizer preview.
=> Load the full size of the logo in customiser when previewing

changelog.txt, functions.php, package.json, style.css
v1.1.0-beta.3
- New: Responsive control for the grid settings for the shop page.
- Fixed: Styles for the WooCommerce my account pages improved.
- Fixed: Remove extra padding from checkout page form.
- Fixed: Cart page coupon box align to Apply Coupon button.
- Fixed: Single Product variation design improved.
- Fixed: Single Product group products design improved.
- Fixed: WooCommerce select box style updated.
- Fixed: `Remove from cart` icon overlaps the title when the title is larger.
=> Version 1.1.0-beta.3 bumped

inc/compatibility/woocommerce/class-astra-woocommerce.php, inc/compatibility/woocommerce/customizer/sections/layout/woo-shop.php
=> Woo default

inc/compatibility/woocommerce/class-astra-woocommerce.php, inc/compatibility/woocommerce/customizer/sections/layout/woo-shop.php, inc/theme-update/class-astra-theme-update.php
Backward compatibility added for default values
=> Woo backward

changelog.txt, functions.php, package.json, style.css
v1.1.0-beta.4
- New Added Product image hover style option.
- New Display outside Custom Menu Item option added in Layout -> Primary Header.
- Fixed Updated Single product group product style.
- Fixed Updated Tracking order pages design.
- Fixed Updated Checkout Page payment box style.
- Moved Cart in Menu option moved to Layout -> Primary Header -> Custom Menu Item.
=> Version v1.1.0-beta.4 bumped

inc/compatibility/woocommerce/class-astra-woocommerce.php, inc/compatibility/woocommerce/customizer/sections/layout/woo-shop.php, inc/extras.php, inc/theme-update/class-astra-theme-update.php
Fixed sidebar and container issue on category pages.
=> Woo sidebar layout

changelog.txt, functions.php, languages/astra.pot, package.json, style.css
v1.1.0
- New: Added Woocommerce complete support.
- New: Added option for Custom Menu Item to Display Outside Menu in primary header.
- New: Organized customizer layout panels.
- Fixed: Missing Structured Data microformat.
=> Version 1.1.0 bumped

inc/class-astra-after-setup-theme.php, inc/compatibility/woocommerce/class-astra-woocommerce.php
Improve the filter for disabling WooCommerce support so that WooCommerce not supported warning is not displayed in the admin
=> Add support for WooCommerce before the class is loaded for WooCommcrce

inc/blog/blog-config.php
Read more doesn't appear on infinite loading of posts.
=> Fixed read more issue in in infinite scrolling

changelog.txt, functions.php, languages/astra.pot, package.json, style.css
- Fixed: WooCommerce shortcode grid style conflict.
- Fixed: WooCommerce cart option renamed to Cart Page.
=> Version 1.1.4 bumped

changelog.txt, functions.php, languages/astra.pot, package.json, style.css
- Improvement: Slightly improved the size of WooComerce header cart icon for small devices for better accessibility.
- Improvement: Improved woocommerce invalid input field default color.
- Fixed: Alignment of empty cart message to the left in header cart.
- Fixed: Updated the size of coupon button for small devices.
- Fixed: Removed single product tabs background color.
- Fixed: Updated the position of product category widget counts to the right.
=> Woo next update

inc/blog/blog-config.php
=> Reduce unnecessary escaping when rendering tags and categories.

inc/core/class-theme-strings.php
Use correct Next/Previous post when in RTL mode.
=> Next prev arrows rtl

languages/astra.pot
- Fixed: Missing port file string updated.
=> pot file missing string added

inc/compatibility/woocommerce/class-astra-woocommerce.php, inc/core/common-functions.php
Common function hex to rgba added
=> Common function hex to rgba added

inc/customizer/class-astra-customizer-sanitizes.php
Sanitize responsive slider for tablet & mobile saved default value to attribute minimum value.
=> Sanitize Responsive Slider fixed

inc/extras.php
- Fixed: Shortcode support added for Footer bar custom text section.
=> Footer custom text shortcode support added

assets/fonts/google-fonts.json, changelog.txt, functions.php, inc/compatibility/woocommerce/customizer/sections/section-container.php, languages/astra.pot, package.json
- Fixed: Added shortcode support for Footer bar custom text section.
- Improvement: Updated Container layout strings for Default, Pages, Blog Posts, Blog Archives & WooCommerce.
- Improvement: Updated strings for Body & Content Font Family & Font Weight.
=> Version 1.2.3 bumped

Gruntfile.js, package.json
add version number to the generated zip file using `grunt release`
=> Added grunt commands to bump the version

comments.php
- Added filter `astra_commnets_title` for comments title
=> Added filter  for comments title

inc/extras.php
- Load the full size of the post thumbnail by default, Pass the value through a filter.
=> load full image size by default from post featured image

inc/core/class-astra-admin-settings.php
- New: Added Cloudways Recommended Hosting information to the welcome page.
=> Added Cloudways link to welcome page

inc/class-astra-dynamic-css.php
Fixed: Font size set in customizer for the body is not being applied correctly for tablet/mobile
Fixes #487
=> Apply correct font-size for tablet/mobile which is selected in the Customizer

assets/fonts/google-fonts.json, changelog.txt, functions.php, languages/astra.pot, package.json, style.css
- New: Added Cloudways Recommended Hosting information to the welcome page.
- Fixed: Single product variations fields added from the third party plugin not align properly.
- Fixed: Font size set in customizer for the body is not being applied correctly for tablet/mobile
=> Version 1.2.6 bumped

inc/extras.php
- Fixed: Footer current year not showing in some languages.
=> Footer current year need not be translated

inc/blog/blog-config.php
- Improvement: Modify the read more link text for the read more tag from content editor.
=> Modify The Read More Link Text

Gruntfile.js, changelog.txt, languages/astra.pot, package.json, style.css
- New: Added Elementor pro 2.0 Support. This also fixes the problem some users were facing related to unusual margins below header when trying out Elementor Pro 2.0 Beta versions.
- New: Introduced new actions and filters for Blog Archive / Single Post template.
- Improvement: Modify the read more tag style which added from content editor.
- Fixed: Few of the Google fonts were not rendered correctly.
- Fixed: Product search widget button text having more padding and causing the text to fall on two lines.
- Fixed: WooCommerce composite products plugin conflict on Single Product Page.
- Fixed: Footer current year does not render correctly for a few languages.
=> Version 1.2.7 bumped

inc/extras.php
* Added `astra_site_title_tag` filter to change site title tags
=> Add astra_site_title_tag filter

inc/compatibility/class-astra-elementor-pro.php
=> Fix: Elementor pro theme builder duplicate content for page

inc/class-astra-loop.php
Fixed: If the target rule is selected for 404 & single post then both the content are visible to 404 page.
=> Fixed: If 404 is selcted from themer

inc/compatibility/woocommerce/class-astra-woocommerce.php
* Fix: Learndash + LearnDash WooCommerce + Astra errors
=> Fix: Learndash + LearnDash WooCommerce + Astra errors

inc/customizer/custom-controls/background/background.js, inc/customizer/custom-controls/background/class-astra-control-background.php, inc/customizer/custom-controls/color/color.js
This was due to duplicate wpColorPicker() being called on color picker from background param
=> Fix: 403 and 404 errors in customizer in some sites 

changelog.txt, functions.php, package.json, style.css
Improvement: Add icon for the LifterLMS My certificates link in My account page. Switch certificate icon with achievements icon.
Improvement: Add icon for the LifterLMS Social Learner link.
Improvement: Added filter for editor style.
Improvement: Increased site header z-index to 99 to fix compatibility with third-party modules.
Improvement: Remove post navigation from LifterLMS Assignments single posts (Credits @thomasplevy)
Improvement: Add Astra theme fields to LifterLMS builder settings (Credits @thomasplevy)
Fix: 403 and 404 errors in customizer in some sites.
Fix: Learndash + LearnDash WooCommerce + Astra errors.
Fix: Mobile menu is displayed for until the page is completely loaded.
Fix: Variations product style issue with Stripe Payment Gateway.
Fix: Don't override the meta settings …
=> Changelog & Version bump Version 1.3.3

Gruntfile.js, inc/customizer/class-astra-customizer.php, inc/customizer/custom-controls/heading/class-astra-control-heading.php, inc/customizer/custom-controls/heading/heading.css, inc/customizer/custom-controls/heading/heading.scss, inc/customizer/customizer-controls.php, inc/customizer/sections/layout/header.php
- New Heading param introduced.
=> New heading param

inc/compatibility/woocommerce/class-astra-woocommerce.php
* Fix: learndash woocommerce plugin warning in dashboard
=> Fixed learndash woocommerce plugin warning in dashboard

inc/class-astra-dynamic-css.php
- Fixed: 1px Border gets applied to toggle button on update
=> remove border css from menu toggle fill style

inc/extras.php
Fix: navigation disappears on breakpoint width resolution
=> navigation disappears on breakpoint width resolution

changelog.txt
v1.4.0
- New: Introduced options for Mobile Header.
- New: Toggle Button Style added for Primary Header.
- New: Added option to Hide custom menu item on mobile for Primary Header.
- New: Added option to Mobile Header Order on mobile when Custom menu item is selected as Take custom menu item outside.
- Improvement: Move Site Identity section under the Layout -> Header section.
=> Changelog updatded

inc/customizer/custom-controls/responsive-spacing/responsive-spacing.css, inc/customizer/custom-controls/responsive-spacing/responsive-spacing.scss
* Remove Bold from spacing param
=> remove bold css from spacing param

assets/css/unminified/compatibility/woocommerce/woocommerce-rtl.css, assets/css/unminified/compatibility/woocommerce/woocommerce.css, inc/customizer/sections/layout/header.php, inc/extras.php, sass/site/compatibility/woocommerce/woocommerce.scss
* String change from custom item menu to last items in menu.
* Change string from header to header layout.
=> String changes

inc/customizer/sections/layout/header.php
* Added opacity option in primary menu border bottom color
=> added opacity option

inc/customizer/register-panels-and-sections.php
* Re-organize primary menu section
=> reoganize primary menu section

inc/compatibility/class-astra-elementor.php
* Updated x-index value for element overlay class
=> increase z-index of elementor overlay class

inc/theme-update/class-astra-theme-update.php
* Fix: retina checkbox not working on the update
=> Retina checkbox fixes

inc/compatibility/woocommerce/customizer/sections/layout/woo-shop.php
Product per page can be set to max 100
=> Woo shop no of products

changelog.txt, inc/customizer/configurations/layout/class-astra-footer-layout-configs.php, inc/customizer/configurations/layout/class-astra-header-layout-configs.php, inc/customizer/configurations/layout/class-astra-site-layout-configs.php
* Add dependencies for site layout
=> Customizer site layouts

inc/customizer/configurations/typography/class-astra-body-typo-configs.php
- Fixed: Paragraph margin-bottom not visible in customizer
=> Fixed: Paragraph margin bottom not visible in customizer

inc/core/common-functions.php
* Update foreground default dark color hex value.
=> Foreground color fixes

inc/compatibility/lifterlms/class-astra-lifterlms.php
=> Fixed: Incorrect closing tag fixed in lifetrlms compatibility file

readme.txt
* Added liscence for wp-color-picker-aplha in readme file
=> add wp color picker alpha js to liscence in read me file

style.css
* Added licensed images link in style.css file
=> Images license

inc/class-astra-dynamic-css.php
* Fix: Custom menu item is not center aligned
=> Fix: Custom menu item alignment issue

inc/assets/css/astra-admin.css
* Fix: notice logo alignment issue
=> Fix: notice logo alignment issue

Gruntfile.js, inc/assets/css/astra-admin-menu-settings-rtl.css, inc/assets/css/astra-admin-rtl.css, inc/core/class-astra-admin-settings.php
* generate astra admin css rtl files
=> generate astra admin rtl files

inc/core/class-astra-theme-options.php
=> change default values

inc/blog/blog-config.php
* Added a new filter post_meta_separator to change the post meta separator symbol.
=> add a new filter to change the post meta separator

inc/core/class-astra-admin-settings.php, inc/lib/notices/class-astra-notices.php
- Updated rating markup in WordPress admin.
=> Added rating markup condition

inc/class-astra-after-setup-theme.php
-  should be correctly  applied depending on the conditions set in the customizer for container
=> Fix: featured images not being fullwidth since #887

inc/compatibility/lifterlms/class-astra-lifterlms.php
* Added a new filter astra_enable_lifterlms_integration to remove lifterlms compatibility
=> added a new filter astra_enable_lifterlms_integration

changelog.txt, functions.php, languages/astra.pot, package.json, style.css
- New: Added Easy Digital Downloads complete support.
- Fix: Featured images not getting full width.
- Fix: Gutenberg embeds not responsive.
=> Version 1.5.5 changelog

inc/customizer/configurations/layout/class-astra-site-identity-configs.php
* changed the minimum value accepted for logo size from 50 to 0
=> changed the minimum value accepted for logo size

inc/class-astra-after-setup-theme.php
which do not override content width for the post types
=> Set correct content_width for single posts on custom post types

functions.php, inc/core/class-astra-theme-options.php, inc/theme-update/class-astra-theme-update.php, style.css
* Added default value true for inline title and logo option.
=> Inline title logo fix

inc/assets/css/block-editor-styles-rtl.css, inc/assets/css/block-editor-styles.css, inc/core/class-astra-enqueue-scripts.php, inc/core/class-gutenberg-editor-css.php, sass/admin/block-editor-styles.scss
- Fix: Edit with Elementor button not correctly styled in Gutenberg.
- Fix: Columns block having extra spacing.
- Fix: Add spacing between media uploader buttons.
- Fix: Add a box background color to Gutenberg when no color is set from customizer.
=> Gutenberg fixes

inc/addons/transparent-header/classes/dynamic-css/dynamic.css.php
Fixed: Sticky colors are not working when we enable transparent header
=> Sticky transparent background fix

inc/customizer/configurations/typography/class-astra-archive-typo-configs.php, inc/customizer/configurations/typography/class-astra-body-typo-configs.php, inc/customizer/configurations/typography/class-astra-content-typo-configs.php, inc/customizer/configurations/typography/class-astra-header-typo-configs.php, inc/customizer/configurations/typography/class-astra-single-typo-configs.php, inc/customizer/custom-controls/divider/class-astra-control-divider.php
* Remove top separator from Typography and colors sections.
* Moved Archive Box typo option to the bottom of the section.
=> Customizer improverments

functions.php, inc/core/class-astra-theme-options.php, inc/theme-update/class-astra-theme-update.php, style.css
* Change default value for Blog Archive Post Title
=> Change post title default

inc/addons/transparent-header/classes/dynamic-css/header-sections-dynamic.css.php
* Fix transparent above header color not working
=> Above header transparent fixes

inc/addons/transparent-header/classes/dynamic-css/dynamic.css.php
colors are being inherited from primary header.
=> Fix: background color for transparent above and below fix.

functions.php, inc/core/class-astra-attr.php, inc/extras.php
This will allow adding HTML markup easily in the theme
=> Add Astra_Attr to Astra Theme

changelog.txt, functions.php, package.json, style.css
- Fix: Menu toggle not working when the window is resized.
- Fix: Block editor content width not exactly same as the frontend.
- Fix: LearnDash sortable elements working incorrectly.
- Fix: Submenu does not open incorrect sides when using RTL mode.
=> Version 1.6.5

inc/extras.php
[Update] -> Added filter to return affiliate id to the ninja forms
=> [Update] -> Added filter to return affiliate id to the ninja forms

inc/core/class-astra-admin-settings.php
[Fix] -> disable notice when Astra White Label is on.
=> Notice appear white label fix

changelog.txt, inc/extras.php
=> Fix: Incorrect markup being displayed for the small footer widget areas. 

inc/core/class-gutenberg-editor-css.php
added edit page in page array to apply background color for the custom post type.
=> added edit page in page array to apply bg color

inc/addons/breadcrumbs/customizer/class-astra-breadcrumbs-color-configs.php
Changing the strings like page header color options strings.
=> Changing color options strings

Gruntfile.js
=> New: Automatically replace x.x.x from function doc to version number.

inc/customizer/custom-controls/settings-group/settings-group.css, package-lock.json, package.json
* Improve group param popup and tabs design
=> improve popup and tabs design

inc/customizer/configurations/buttons/class-astra-customizer-button-configs.php, inc/customizer/configurations/layout/class-astra-header-layout-configs.php
Updated button option condition and priority.
=> Primary header button group update

inc/customizer/configurations/layout/class-astra-footer-layout-configs.php
added group for typo in footer section
=> added group for typo in footer section

inc/addons/breadcrumbs/customizer/class-astra-breadcrumbs-color-configs.php, inc/addons/breadcrumbs/customizer/class-astra-breadcrumbs-typo-configs.php
- Updated breadcrumbs typo grouping position and added divider.
=> updated breadcrumb section typo grouping position

assets/js/unminified/customizer-preview.js, inc/class-astra-dynamic-css.php, inc/customizer/configurations/colors-background/class-astra-advanced-footer-colors-configs.php, inc/customizer/configurations/layout/class-astra-footer-layout-configs.php
Added Footer widget's color group
=> Footer widget customizer improvement

inc/customizer/configurations/colors-background/class-astra-footer-colors-configs.php
=> Remove sections old

inc/customizer/custom-controls/responsive-color/class-astra-control-responsive-color.php, inc/customizer/custom-controls/responsive-slider/class-astra-control-responsive-slider.php, inc/customizer/custom-controls/responsive/class-astra-control-responsive.php, inc/customizer/custom-controls/settings-group/settings-group.js
- Group Popup should be closed once we move to another section
- Group param option should match responsive mode
=> Group settings popup improvement

inc/customizer/custom-controls/settings-group/settings-group.js
=> popup close issue

inc/customizer/configurations/layout/class-astra-blog-single-layout-configs.php, inc/customizer/configurations/typography/class-astra-single-typo-configs.php
Single post typo position update
=> updated priority of option

inc/customizer/configurations/layout/class-astra-footer-layout-configs.php
* Remove unwanted sections and group from the theme
=> remove unwanted sections

inc/addons/breadcrumbs/class-astra-breadcrumbs-loader.php
- Fix: Breadcrumb typography not working on frontend
=> Breadcrumb typography not working on frontend

inc/customizer/custom-controls/heading/heading.css, inc/customizer/custom-controls/heading/heading.scss
* Fix margin when heading param is used first in the section.
=> Fix: margin top when heading param is used first in the section

inc/customizer/class-astra-customizer.php
* Load individual CSS and JS files of all the controls that are used inside the group settings control.
=> Param files not loading

inc/customizer/custom-controls/heading/heading.css, inc/customizer/custom-controls/heading/heading.scss
Update .customize-control-ast-heading class.
=> Ast heading spacing issue

composer.lock, inc/core/common-functions.php, inc/customizer/configurations/buttons/class-astra-customizer-button-configs.php, inc/customizer/custom-controls/settings-group/settings-group.js
* Fix: Default values not working with astra_get_option_by_group function
=> Get option by group fixes

inc/extras.php
* Fix: Hamburger icon visible even after disabled on mobile and menu is also disabled
=> Fix: Hamburger icon visible even after disabled on mobile and menu is also disabled

inc/customizer/configurations/layout/class-astra-header-layout-configs.php
Fix: button postMessage issue by update wrong selector
=> Fix: button postMessage issue

inc/addons/transparent-header/classes/sections/class-astra-customizer-transparent-header-configs.php
updated group menu label in the transparent header
=> updated group menu label in transparent header

inc/customizer/custom-controls/background/background.js, inc/customizer/custom-controls/background/class-astra-control-background.php
…und image param in Customizer.
=> Fix: More Settings/Less Settings not working properly for Background image param in Customizer.

inc/customizer/configurations/layout/class-astra-footer-layout-configs.php, inc/customizer/configurations/layout/class-astra-header-layout-configs.php
=> Fix string

composer.json, composer.lock
Could you update the lock file? `composer update --lock`
=> Normalize composer config

assets/css/unminified/customizer-controls.css, inc/compatibility/edd/customizer/sections/class-astra-edd-container-configs.php, inc/compatibility/lifterlms/customizer/sections/class-astra-lifter-container-configs.php, inc/compatibility/woocommerce/customizer/sections/class-astra-woo-shop-container-configs.php, inc/compatibility/woocommerce/customizer/sections/layout/class-astra-woo-shop-layout-configs.php, inc/customizer/configurations/layout/class-astra-footer-layout-configs.php
1) Media Uploader title not appearing
2) Base Colors - Background Heading is still appearing in new beta package.
3) Remove Mega Menu Column Heading from Popup in Sticky Header - Primary Header
4) Capitalize stings
5) Need to add separator headings
=> Random fixes

inc/customizer/class-astra-customizer.php
=> Warning fix

inc/core/class-astra-admin-settings.php
=> Sidebar icon css

inc/customizer/custom-controls/typography/typography.js
=> updated custom font condition for select weight option

inc/addons/breadcrumbs/class-astra-breadcrumbs-loader.php
=> [Fix] -> Site title line height default fix

changelog.txt
Fix: RTL fixes for customizer options.
=> Updated changelog for rtl fixes

inc/class-astra-dynamic-css.php
=>  Fix: Default button styling support for Gutenberg button using class 'ast-gtn-btn'

inc/extras.php, sidebar.php
`astra_attr()` allows to filter the markup and remove the attributes.
=> refactor: use astra_attr to build markup where schema tags are added.

inc/class-astra-dynamic-css.php
=> revert: gutenberg button style support

inc/class-astra-dynamic-css.php
=> fix: Paragraph margin CSS option not working for single post / Page fix.

changelog.txt, functions.php, inc/extras.php, package.json, sidebar.php, style.css, template-parts/content-blog.php, template-parts/content-page.php, template-parts/content-single.php, template-parts/content.php
fixed markup issue of space for header and footer
=> Fix: markup issue for header and footer

inc/class-astra-after-setup-theme.php
* Added style and script html5 theme support
=> added style and script html5 theme support

functions.php, inc/compatibility/class-astra-yoast-seo.php
- Custom layouts should be hidden from sitemap
=> feat: Custom layouts should be hidden from sitemap

inc/class-astra-dynamic-css.php, inc/theme-update/astra-update-functions.php, inc/theme-update/class-astra-theme-background-updater.php
=> revert: Remove database migration for .hidden CSS compatibility.

inc/extras.php, inc/schema/class-astra-creativework-schema.php, inc/schema/class-astra-person-schema.php
Fix: added author instead of author-name in creative work schema.
=> Added author instead of author-name in creative work schema

inc/extras.php
Changed the Theme name in credit link text in the footer
=> Change: Theme name in credit link text shortcode

inc/extras.php
Added action - https://github.com/impress-org/givewp-snippet-library/blob/master/admin-functions/modify-givewp-addons-admin-link.php
=> refactor: Affiliate givewp form

inc/class-astra-dynamic-css.php, inc/theme-update/astra-update-functions.php, inc/theme-update/class-astra-theme-background-updater.php
…applied to new users and not to the existing users.
=> fix: Button Line height removed from existing users. 

inc/customizer/configurations/layout/class-astra-header-layout-configs.php
- Edit icons are showing in next-release branch.
=> fix: Edit button fix

Gruntfile.js, README.md, languages/astra.pot, package-lock.json, package.json, readme.txt
- Added new grunt readme function in gruntfile JS
- Updated README file
- Deprecated plugin removed from the readme
- Child theme knowledge link updated with the new link
=> improvement: Update readme file

Gruntfile.js, inc/customizer/custom-controls/class-astra-customizer-control-base.php
Reverts brainstormforce/astra#1619
=> revert: "chore: Added dev provision to load individual addons script if SCRIPT_DEBUG"

inc/compatibility/edd/class-astra-edd.php
- Minimized line of code
- Managed selectors with existing CSS
=> chore: Minimized line of code

functions.php, inc/theme-update/class-astra-theme-background-updater.php, style.css
- Version updated to run the batch process
=> chore: Version updated to run batch process

inc/compatibility/class-astra-amp.php, inc/core/class-gutenberg-editor-css.php, inc/core/common-functions.php
- Replaced all static mobile & tablet breakpoints to dynamic which required in rendering dynamic CSS
=> chore: Replaced static default breakpoints to dynamic

inc/customizer/class-astra-font-families.php
Reverts brainstormforce/astra#1597
=> revert: "fix: Google Font loading issue with FS_MTHOD ftpext."

functions.php, inc/theme-update/class-astra-theme-background-updater.php, style.css
- Updated version numbers to run the batch process
=> chore: Version update to run batch process

inc/class-astra-dynamic-css.php, inc/compatibility/woocommerce/class-astra-woocommerce.php
- Cart page product-thumbnail issue fixed with responsive
- ast-container CSS corrected with max-width mobile-breakpoint px
=> fix: Cart page product-thumbnail issue fixed with responsive

inc/compatibility/woocommerce/class-astra-woocommerce.php
- WooCommerce Product shortcode issue fixed for mobile devices as it's aligned in only one column
=> fix: Woo Products Grid issue fixed for mobile devices

composer.lock, inc/class-astra-dynamic-css.php, package-lock.json
- Added static responsive CSS to dynamic
- Removed unused variables from dynamic-css as per Sonarlint suggestion
=> fix: Added static responsive CSS to dynamic

inc/extras.php
- Updated version to the latest release to remove previous BG control
=> fix: Version updated to remove previous site-layout-bg-config

inc/customizer/custom-controls/responsive-background/class-astra-control-responsive-background.php
=> fix: Added HTML entities in responsive param case

changelog.txt
- Updated changelog string for Sstarter Templates plugin strings
=> chore: Updated changelog file

inc/core/class-astra-enqueue-scripts.php
- Removed admin_body_class support in case of custom layout post type
=> improvement: Custom layout GB support compatibility

inc/compatibility/woocommerce/class-astra-woocommerce.php, inc/extras.php
Added Breadcrumb Position and Mobile Menu Style.
Added data in the array. https://github.com/brainstormforce/astra/blob/master/inc/extras.php#L1935
By sending the request to our app.
=> chore: Analytics data for Breadcrumb Position and Mobile Menu Style.

inc/customizer/configurations/layout/class-astra-site-identity-configs.php, inc/extras.php
Moved theme settings of BSF Analytics inside 'astra_theme' key.
This includes changes in the filter for bsf analytics.
Locally by checking the final array values.
=> fix: Moved theme settings of BSF Analytics inside 'astra_theme' key.

README.md, changelog.txt, inc/core/class-astra-admin-settings.php, inc/theme-update/astra-update-functions.php, languages/astra.pot, package.json, readme.txt, style.css
v2.5.2
- Fix: Footer Widgets background color option not working for new users.
Non breaking changes.
Tested for existing and new users.
=> chore: v2.5.2 update

README.md, inc/core/class-astra-admin-settings.php, inc/customizer/custom-controls/class-astra-customizer-control-base.php, inc/customizer/custom-controls/responsive-background/class-astra-control-responsive-background.php, languages/astra.pot, readme.txt, style.css
Fixes theme review reported issues/improvements.
https://themes.trac.wordpress.org/ticket/87851
Non-breaking changes. Only few tweaks.
=> Theme review fixes

inc/customizer/builder/customizer/configuration/footer/widget/class-astra-footer-widget-component-configs.php
Trello task - https://trello.com/c/mVqGJFPX/235-footer-widget
- Just appearance changes.
=> feat: Footer Widget changes.

inc/customizer/builder/class-astra-builder-admin.php
Trello task - https://trello.com/c/V9kPhJxj/239-add-customizer-link-on-astra-options-page
https://a.cl.ly/4gu9pZYd
New feature (non-breaking change which adds functionality) 
- Link to Customizer.
=> feat: Added a link to customizer in Astra Options.

inc/customizer/builder/class-astra-builder-controller.php, inc/customizer/builder/customizer/configuration/header/mobile-trigger/assets/js/customizer-preview.js
- Fixed some issues faced.
- Checked for any console or PHP errors.
=> fix: Fixed some issues faced.

inc/customizer/builder/class-astra-builder-loader.php
Fixed Fatal error for defined constants for Control count.
=> fix: Fixed Fatal error for defined constants for Control count.

inc/customizer/builder/customizer/configuration/footer/builder/class-astra-customizer-footer-builder-configs.php, inc/customizer/builder/customizer/defaults/class-astra-options-default.php
=> fix: Footer render issue

inc/customizer/builder/customizer/configuration/base/configs/class-astra-html-component-configs.php, inc/customizer/builder/customizer/configuration/base/configs/class-astra-social-icon-component-configs.php, inc/customizer/builder/customizer/configuration/class-astra-builder-base-configuration.php, inc/customizer/builder/customizer/configuration/footer/above-footer/class-astra-customizer-above-footer-configs.php, inc/customizer/builder/customizer/configuration/footer/below-footer/class-astra-customizer-below-footer-configs.php, inc/customizer/builder/customizer/configuration/footer/builder/class-astra-customizer-footer-builder-configs.php, inc/customizer/builder/customizer/configuration/footer/copyright/class-astra-customizer-copyright-configs.php, inc/customizer/builder/customizer/configuration/footer/menu/class-astra-customizer-footer-menu-configs.php, inc/customizer/builder/customizer/configuration/footer/primary-footer/class-astra-customizer-primary-footer-configs.php, inc/customizer/builder/customizer/configuration/footer/social-icon/class-astra-customizer-footer-social-icons-configs.php, inc/customizer/builder/customizer/configuration/footer/widget/class-astra-footer-widget-component-configs.php, inc/customizer/builder/customizer/configuration/header/above-header/class-astra-customizer-above-header-configs.php, inc/customizer/builder/customizer/configuration/header/below-header/class-astra-customizer-below-header-configs.php, inc/customizer/builder/customizer/configuration/header/builder/class-astra-customizer-header-builder-configs.php, inc/customizer/builder/customizer/configuration/header/button/class-astra-header-button-component-configs.php, inc/customizer/builder/customizer/configuration/header/menu/class-astra-header-menu-component-configs.php, inc/customizer/builder/customizer/configuration/header/mobile-trigger/class-astra-customizer-mobile-trigger-configs.php, inc/customizer/builder/customizer/configuration/header/off-canvas/class-astra-customizer-off-canvas-configs.php, inc/customizer/builder/customizer/configuration/header/primary-header/class-astra-customizer-primary-header-configs.php, inc/customizer/builder/customizer/configuration/header/search/class-astra-header-search-component-configs.php, inc/customizer/builder/customizer/configuration/header/site-identity/class-astra-customizer-site-identity-configs.php, inc/customizer/builder/customizer/configuration/header/sticky/class-astra-customizer-sticky-header-builder-configs.php, inc/customizer/builder/customizer/configuration/header/transparent/class-astra-customizer-transparent-header-builder-configs.php, inc/customizer/configurations/layout/class-astra-site-identity-configs.php
- Refactored an array with defined constants.
=> fix: Code constant refactor

functions.php, inc/assets/js/admin-settings.js, inc/builder/class-astra-builder-loader.php, inc/builder/controllers/class-astra-builder-widget-controller.php, inc/builder/markup/class-astra-builder-header.php, inc/core/builder/class-astra-builder-admin.php, inc/core/builder/class-astra-builder-helper.php, inc/customizer/class-astra-builder-customizer.php, inc/customizer/configurations/builder/header/class-astra-customizer-primary-header-configs.php, inc/theme-update/astra-update-functions.php, inc/theme-update/class-astra-theme-background-updater.php
- Issue with the first click on Migrate button.
- Removed dependent `Delete old options` code.
=> refactor: Migration logic refactor and removed some extra unwanted code too.

inc/customizer/configurations/builder/footer/class-astra-customizer-copyright-configs.php, template-parts/footer/builder/components.php
- Fixed copyright partial rendering.
=> fix: Partial rendering copyright

inc/builder/markup/class-astra-builder-footer.php, template-parts/footer/builder/components.php, template-parts/header/builder/components.php
Action added to fetch HF components from addon. - [[Task]](https://trello.com/c/JKv0KmSg/294-separate-addon-code-html-css)
Refactor.
=> refactor: Action added to fetch HF components from addon.

template-parts/footer/builder/components.php, template-parts/header/builder/components.php
Renamed action for components render.
=> refactor: Renamed action for components render.

inc/admin-functions.php, inc/builder/class-astra-builder-loader.php, inc/class-astra-constants.php, inc/customizer/class-astra-builder-customizer.php, inc/customizer/configurations/builder/header/class-astra-customizer-header-builder-configs.php, inc/customizer/configurations/builder/header/class-astra-customizer-site-identity-configs.php, inc/customizer/configurations/layout/class-astra-site-identity-configs.php
=> fix: Menu Sequence and Logo issue

template-parts/header/builder/components.php
- Trello task - https://trello.com/c/ksJfMdRl/311-what-does-this-code-do
- Removed unused code.
- Checked Social, Button, HTML & Logo in mobile.
=> fix: Removed unwanted code

inc/builder/type/base/dynamic-css/widget/class-astra-widget-component-dynamic-css.php
refactor: Updated options name
=> refactor: Updated options name

composer.lock, inc/class-astra-dynamic-css.php, package-lock.json, package.json
- In Gutenberg new update, they have added display:flex; property for buttons. Due to which all buttons are getting left aligned - 
- Change max-width with simple width - https://share.getcloudapp.com/6quPjdvP 
https://share.getcloudapp.com/QwukOPEz
(Refer to this video - https://share.getcloudapp.com/qGuvQ97L)
I have tested this by importing the customizer settings and pages of the designer's site.
=> fix: Title and Gutenberg button alignment fixes. 

composer.json, composer.lock, functions.php, inc/class-astra-dynamic-css.php
Checked the issues reported on the website demos.
Checked by importing the same pages and some demo random sites.
=> fix: Gutenberg cover block container width CSS cases.

inc/customizer/class-astra-customizer-sanitizes.php
https://trello.com/c/IwmsckaZ/764-we-need-a-way-to-allow-negative-margins
Fix.
Enter negative margins and check in frontend.
=> fix: Allowed negative margins

inc/builder/type/header/edd-cart/dynamic-css/dynamic.css.php, inc/builder/type/header/woo-cart/dynamic-css/dynamic.css.php, inc/compatibility/edd/class-astra-edd.php, inc/compatibility/woocommerce/class-astra-woocommerce.php, inc/core/builder/class-astra-builder-helper.php, inc/customizer/class-astra-builder-customizer.php, inc/customizer/configurations/builder/header/class-astra-customizer-edd-cart-configs.php, inc/customizer/configurations/builder/header/class-astra-customizer-woo-cart-configs.php
https://trello.com/c/5FQGWIjm/558-cart-header-edd-woo
fix.
=> fix: Woo and EDD Cart issues

inc/addons/transparent-header/classes/sections/class-astra-customizer-transparent-header-configs.php
Trello task - https://trello.com/c/3PUmX9am/818-backward-conditions-update-on-basis-of-new-context
- Checked conditions to display options.
=> fix: Context Logic for Transperent Header.

inc/customizer/configurations/layout/class-astra-header-layout-configs.php
=> fix:resolved context hide show element issue

inc/customizer/configurations/builder/base/class-astra-divider-component-configs.php
- Trello task - https://trello.com/c/8yqOULSU/820-divider-compatibility-with-new-context-logic
- Check conditions.
=> fix: Divider compatibility with new context Logic.

inc/core/builder/class-astra-builder-options.php
[Task](https://trello.com/c/fEKWHWjW/806-footer-builder-on-responsive-device-the-default-layout-should-be-stack)
Enhancement.
=> fix: Default options for Footer layout

inc/assets/css/ast-builder-customizer-rtl.css, inc/assets/css/ast-builder-customizer.css
- Removed 10% width for footer dropped components
- Aligned all items centrally
- https://a.cl.ly/bLu0GJBg
- CSS updated
- With Footer Builder layout
=> refactor: Updated UI of footer component items alignment

inc/assets/css/ast-builder-customizer-rtl.css, inc/assets/css/ast-builder-customizer.css, inc/builder/type/footer/menu/class-astra-footer-menu-component.php, inc/builder/type/footer/menu/dynamic-css/dynamic.css.php, inc/builder/type/header/menu/assets/js/customizer-preview.js, inc/builder/type/header/menu/dynamic-css/dynamic.css.php, inc/core/builder/class-astra-builder-options.php, inc/customizer/configurations/builder/header/class-astra-customizer-site-identity-configs.php, inc/customizer/configurations/layout/class-astra-site-identity-configs.php, inc/customizer/override-defaults.php
Footer Menu - Responsive Layout
=> feat: Footer Menu - Responsive Layout

inc/compatibility/edd/customizer/sections/layout/class-astra-edd-archive-layout-configs.php
- fix: EDD Product structure Description not displaying
- Description is visible.
=> fix: EDD Product structure Description not displaying

inc/class-astra-mobile-header.php
- Trello task - https://trello.com/c/mitPmxhs/738-menu-issues-multiple-logic
- Submenu arrows visible.
=> fix: Submenu Arrows not visible for Multiple Menus.

template-parts/footer/builder/footer-row.php
feat: New hooks for Footer added for compatibility with HFB Footer markup.
=> feat: New hooks for Footer added for compatibility with HFB Footer markup.

inc/customizer/configurations/builder/header/class-astra-customizer-edd-cart-configs.php, inc/customizer/configurations/builder/header/class-astra-customizer-woo-cart-configs.php
=> fix: Typo error in Woo/EDD cart

inc/builder/type/header/above-header/assets/js/customizer-preview.js, inc/builder/type/header/above-header/dynamic-css/dynamic.css.php, inc/builder/type/header/below-header/assets/js/customizer-preview.js, inc/builder/type/header/below-header/dynamic-css/dynamic.css.php, inc/builder/type/header/primary-header/assets/js/customizer-preview.js, inc/builder/type/header/primary-header/dynamic-css/dynamic.css.php
Messed up line-height.
https://share.getcloudapp.com/DOuooWbO
=> fix: Line height issue with menu

footer.php, header.php, inc/builder/controllers/class-astra-builder-ui-controller.php, inc/builder/markup/class-astra-builder-header.php, inc/class-astra-loop.php, inc/core/builder/class-astra-builder-helper.php, index.php, sidebar.php, template-parts/content-blog.php, template-parts/footer/builder/desktop-builder-layout.php, template-parts/header/builder/desktop-builder-layout.php, template-parts/header/builder/mobile-builder-layout.php
- Removed blank spaces from the final generate HTML.
=> improvement: removed blank spaces from generated html

inc/class-astra-dynamic-css.php
fix: Global button hover colours not being applied to HF Buttons issue fixed.
=> fix: Global button hover colors not being applied to HF Buttons issue fixed.

inc/customizer/configurations/builder/class-astra-builder-base-configuration.php
Removed Hide on Desktop visibility for Header Widgets. [Task](https://trello.com/c/fNSATv24/846-need-to-add-2-widgets-in-astra-theme-header)
Bug-fix (non-breaking change which fixes an issue)
=> fix: Removed Hide on Desktop visibility for Header Widgets.

inc/customizer/configurations/builder/footer/class-astra-customizer-footer-builder-configs.php, inc/customizer/configurations/builder/header/class-astra-customizer-header-builder-configs.php
=> fix: Added a config for builders

inc/theme-update/astra-update-functions.php
- Trello task - https://trello.com/c/zRXqEr9c/797-batch-process-for-migration
- Bug fix (non-breaking change which fixes an issue)
- Check if old settings get migrated in a proper way such as Old & new Sticky Header should look the same.
=> improvement: Batch Process migration logic for Sticky Header.

inc/builder/markup/class-astra-builder-header.php, inc/markup-extras.php
fix: Removed duplicate function to render header html.
=> fix: Sticky rendering merged.

inc/theme-update/astra-update-functions.php
- Trello task - https://trello.com/c/zRXqEr9c/797-batch-process-for-migration
Bugfix (non-breaking change that fixes an issue)
- Add Widgets in master branch & then switch to our branch the widgets should be migrated without any php errors.
-
=> fix: Resolve issues in widget migration.

inc/builder/type/footer/copyright/class-astra-footer-copyright-component-loader.php, inc/builder/type/footer/menu/class-astra-footer-menu-component-loader.php, inc/builder/type/header/mobile-menu/class-astra-mobile-menu-component-loader.php, inc/builder/type/header/mobile-trigger/class-astra-mobile-trigger-loader.php, inc/builder/type/header/search/class-astra-header-search-component-loader.php, inc/builder/type/header/site-identity/class-astra-header-site-identity-component-loader.php
Removed unwanted extra duplicate declaration of local variables.
Optimisation
=> perf: Removed unwanted extra duplicate declaration of local variables.

inc/addons/transparent-header/classes/sections/class-astra-customizer-transparent-header-configs.php
fix: Transparent header context
=> fix: Transparent header context

inc/theme-update/astra-update-functions.php
-  Added migration for Sticky Header Button.
- Bugfix (a non-breaking change that fixes an issue)
- Added Sticky Header Button Settings in the master branch then switch to this branch, the settings should be migrated.
=> fix: Added Sticky Header Button Migration Logic.

inc/compatibility/lifterlms/customizer/sections/layout/class-astra-lifter-general-configs.php
- fix: Added a file which was removed causing warnings.
=> fix: Added file

inc/admin-functions.php, inc/builder/type/header/menu/class-astra-header-menu-component-loader.php, inc/class-astra-mobile-header.php, inc/core/builder/class-astra-builder-options.php, inc/core/class-astra-enqueue-scripts.php, inc/customizer/configurations/builder/header/class-astra-customizer-header-builder-configs.php, inc/customizer/configurations/builder/header/class-astra-header-menu-component-configs.php
=> fix: Added menu operations

inc/theme-update/astra-update-functions.php
https://trello.com/c/y56xKKeg/923-beta-to-beta-update-migration-issue
Install Beta on a new website.
Now update to stable v3.0
You will see console errors in the customizer.
=> fix: Migration issue with Beta to beta update

inc/customizer/configurations/layout/class-astra-footer-layout-configs.php
- fix: footer widget compatibility.
=> fix: Fixed backward compatibility

inc/customizer/astra-pro/class-astra-pro-upgrade-link-configs.php
=> fix: Astra pro notice

inc/core/builder/class-astra-builder-admin.php, inc/theme-update/astra-update-functions.php
Task - [Link](https://trello.com/c/YEFxfhDw/930-migrate-on-migration-click)
=> feat: Invoke migration batch process on click of the migration button.

changelog.txt
Added changelog for is_component_loaded function optimization.
- Improvements.
=> Component changelog

README.md, changelog.txt, functions.php, languages/astra.pot, package.json, readme.txt, style.css
- Fix: Astra assets cache regeneration issue when Astra Pro is updated to v3.0.0 prior to theme. ( https://wpastra.com/docs/clear-astra-cache/ )
- Fix: UI Tab switching in color options for RTL websites.
- Fix: Builder - Duplicate listing of social icons in customizer.
=> chore: v3.0.1 release.

functions.php
- The version in the theme was wrongly updated.
Bugfix (non-breaking change that fixes an issue)
- No testing required.
=> fix: Updated the correct version in the Theme.

inc/customizer/configurations/builder/footer/class-astra-customizer-footer-builder-configs.php
- Description message updated for Footer Builder
- https://share.getcloudapp.com/KouZWpW2
- With Footer Builder
=> refactor: Description updated for footer builder BG setting

changelog.txt
=> chore: Added changelog

.github/workflows/stale.yml
Mark PRs as stale after 60 days od inactivity.
Close the PRs after the next 120 days of no activity.
=> AST-4 - Setup stale bot action

.github/semantic.yml
The semantic Pull request app has been disabled as well.
=> Remove semantic pull request configuration

inc/customizer/configurations/layout/class-astra-footer-layout-configs.php
- Trello task - https://trello.com/c/ZRoLhNcC/1246-old-header-footer-issues
- Mentioned in the Trello task.
=> fix: Issues in Old Header/Footer found during Final ZIP testing.

inc/addons/heading-colors/customizer/class-astra-heading-colors-configs.php
Task - https://trello.com/c/AStiqHwm/1250-warning-in-customizer-console
Bug-fix.
Go to Global > Typography > Headings
Should not see [such an error](https://drive.google.com/file/d/1YkcjcTxdZ26vXk8_X89X7dQhFaeCZfNG/view?usp=sharing).
=> fix: Fixed a console error in Global > Typography > Headings

inc/customizer/configurations/builder/base/class-astra-button-component-configs.php, inc/customizer/configurations/builder/class-astra-builder-base-configuration.php, inc/customizer/configurations/builder/footer/class-astra-customizer-footer-menu-configs.php, inc/customizer/configurations/layout/class-astra-site-identity-configs.php, inc/customizer/configurations/typography/class-astra-single-typo-configs.php
Task - https://trello.com/c/kwgtUo6n/1223-typography-popup-when-astra-pro-is-active-but-addons-are-inactive-issue
Bug fix
- Footer Menu > Menu Font Size
- Header Buttons > Font Size
- Footer Buttons > Font Size
Test for the above options with font size.
=> fix: Added the Typography addon dependency for Font Size

inc/customizer/configurations/typography/class-astra-archive-typo-configs.php
Seeing a popup for the single option under the Blog section.
https://a.cl.ly/12uobvON
Bug fix
- Keep the Astra Addon active.
- Disable Typography addon.
=> fix: Blog > Blog Archive > Typography Addon dependency issue fixed.

inc/addons/breadcrumbs/class-astra-breadcrumb-trail.php, inc/core/common-functions.php, inc/customizer/class-astra-customizer-sanitizes.php, template-parts/footer/builder/footer-row.php
Fixed SonarLint issues related to curly braces
=> fix: SonarLint curly braces issue

inc/blog/single-blog.php, inc/compatibility/lifterlms/class-astra-lifterlms.php
Fixed SonarLint issues related to commented code in files
=> fix: SonarLint commented code fix

inc/builder/type/header/account/assets/js/customizer-preview.js, inc/builder/type/header/search/assets/js/customizer-preview.js
Fixed SonarLint issues related to identical sub expression in conditional statements
=> fix: SonarLint identical sub expression issue

changelog.txt
Updated the changelog
Non-breaking changes.
=> fix: updated string for changelog.

changelog.txt, inc/core/builder/class-astra-builder-options.php
Task - https://trello.com/c/YPrtXZML/1255-default-unit-not-set-on-header-margin-option
Bug-fix
=> fix: Header Builder margin option default units were missing.

changelog.txt, functions.php, inc/compatibility/class-astra-web-stories.php, phpcs.xml.dist
Brings https://github.com/brainstormforce/astra/pull/2488 to master
=> Add web stories plugin support in Astra

package.json
=> install grunt-cli as dev dependency

bin/scripts/dynamic-css-to-file.js
=> Dynamic CSS audit test

Gruntfile.js
=> Drop the dynamic-css file from build script

.github/workflows/auto-cancel.yml, .github/workflows/simple-size-check.yml, .gitignore, Gruntfile.js, bin/scripts/dynamic-css-to-file.js, package-lock.json, package.json
Writes the dynamic CSS to a file in the assets directory so that this is included in the CSS audit.
This should be merged after #2564
Tested in this PR - https://github.com/brainstormforce/astra/pull/2574#issuecomment-812079028
=> AST-276 Check size of the dynamic CSS

changelog.txt
Added changelog for this #2629
=> chore: added changelog and props for toolset update PR.

changelog.txt, inc/customizer/configurations/layout/class-astra-related-posts-configs.php, inc/customizer/configurations/typography/class-astra-single-typo-configs.php
- Updated correct sequence in Single post section
- https://share.bsf.io/wbuwQ0ev
- With Single Post section
- With General | Design tab
- W/o General | Design tab
- With Free theme
- With Theme + Addon
=> AST-74 - refactor: Updated priorities of control in order to maintain correct sequence in customizer

.github/workflows/release-pr-template.yml
This PR has an action which updates the PR when we add label `Release PR checklist` to the PR with base branch `master` or `dev` or `next-release`.
Title: `Build: Release PR`
Body:
```
---
```
New feature for GitHub action.
=> feat: Release PR checklist action

changelog.txt, inc/builder/type/header/off-canvas/dynamic-css/dynamic.css.php
- Flyout of type left is not working
- https://bit.ly/3e2pzhl
- Bug fix 
- Test with flyout left style
- Also make sure to check every option in off-canvas flyout style
=> AST-411 - fix: Off-canvas - Left flyout style not working.

inc/class-astra-dynamic-css.php, package-lock.json
=> test: Remove HTML font size percentage.

inc/class-astra-dynamic-css.php
=> test: Body font size -> PX to REM causes CLS or not.

inc/extras.php
Reverts brainstormforce/astra#2726
=> Revert "test: removing svg icon temp to check CLS."

inc/class-astra-dynamic-css.php
Reverts brainstormforce/astra#2729
=> Revert "test: Body font size -> PX to REM causes CLS or not."

inc/class-astra-dynamic-css.php, package-lock.json
Reverts brainstormforce/astra#2745
=> Revert "Revert "test: Remove HTML font size percentage.""

inc/class-astra-dynamic-css.php, package-lock.json
Reverts brainstormforce/astra#2746
=> Revert "Revert "Revert "test: Remove HTML font size percentage."""

changelog.txt, inc/core/class-gutenberg-editor-css.php
https://github.com/brainstormforce/astra/pull/2718
=> Cherry picked - #2718

changelog.txt, inc/core/class-gutenberg-editor-css.php
- Reverting Editor selection fixes PR - https://github.com/brainstormforce/astra/pull/2718/
=> revert: Editor selection PR reverted as it will release in next version

changelog.txt, functions.php, inc/builder/type/header/edd-cart/dynamic-css/dynamic.css.php, inc/builder/type/header/woo-cart/dynamic-css/dynamic.css.php, inc/class-astra-dynamic-css.php
- PR - https://github.com/brainstormforce/astra/pull/2712/
=> Cherry prick PR #2712

changelog.txt, inc/class-astra-dynamic-css.php
- Cherry pick
- PR - https://github.com/brainstormforce/astra/pull/2682
=> Cherry pick cart duplicate CSS #2682

README.md, changelog.txt, inc/compatibility/woocommerce/class-astra-woocommerce.php, languages/astra.pot, package-lock.json, package.json, readme.txt, style.css
---
---
- v3.4.3 update preparation
=> Build: Release PR v3.4.3

README.md, functions.php, languages/astra.pot, package-lock.json, package.json, readme.txt, style.css
---
---
v3.4.4 update preparation
=> Build: Release PR v3.4.4

README.md, changelog.txt, functions.php, languages/astra.pot, package-lock.json, package.json, readme.txt, style.css
---
---
- Release v3.4.5 PR
- Fix: Compatibility with Google Web Stories plugin v1.7.0.
=> Build: Release PR v3.4.5

README.md, changelog.txt, functions.php, inc/compatibility/class-astra-web-stories.php, languages/astra.pot, package.json, readme.txt, style.css
---
---
- Google Web Stories class exists check added before running the code.
- This causes Footer Misalignment issue.
Related #2778
[https://share.bsf.io/P8u9ZqLR](https://share.bsf.io/P8u9ZqLR)
Bug fix
=> Build: Release PR fix: Google Web Stories class exists check added before running the code.

changelog.txt
-  Added changelog for  this PR - https://github.com/brainstormforce/astra/pull/2769/files
=> chore: adeed changelog for footer builder issue

functions.php, inc/builder/type/header/above-header/dynamic-css/dynamic.css.php, inc/class-astra-dynamic-css.php, inc/customizer/configurations/layout/class-astra-site-identity-configs.php, inc/extras.php
- Updated beta version check with stable version check
- Previous Beta release PR -
- https://github.com/brainstormforce/astra/pull/2819
- Non-breaking change 
- With Astra v3.5.0 version update
=> AST-526 - refactor: Updated beta version check to stable 3.5.0 version

changelog.txt
Added changelog for v3.5.0
Non breaking changes, text updated.
=> Changelog v3.5.0

inc/customizer/configurations/performance/class-astra-performance-configs.php
- Removed extra text-domain in Astra
- https://share.bsf.io/ApuzkZNJ
=> chore: Corrected text-domain for astra

changelog.txt
- PR suggestion
- https://github.com/brainstormforce/astra/pull/2858#discussion_r650920083
=> chore: Updated changelog sequence

inc/customizer/custom-controls/typography/selectWoo.css
https://wp-astra.atlassian.net/browse/AST-574
https://share.bsf.io/2NuqjWvK
Fix - https://share.getcloudapp.com/geugqBQy
=> AST-574 - fix: cross button alignment on select2

README.md, readme.txt
- Updated assets links for Astra screenshot's images
- Description added here - https://wp-astra.atlassian.net/browse/AST-576
=> AST-576 - refactor: Updated assets images links for Astra screenshot

languages/astra.pot, package-lock.json, searchform.php
---
---
- PR merged - https://github.com/brainstormforce/astra/pull/2875
=> Build: Release PR chore: Updated grunt bump version after mergin PR #2875

package-lock.json, package.json
Node and npm version requirement added in the package.json to notify the devs before installing npm.
Non breaking change
Error when the node version requirement is not met.
=> Node and npm version requirement added in the package.json to notify the devs before installing npm.

searchform.php
https://wp-astra.atlassian.net/browse/AST-579
https://share.bsf.io/12u4gDx1
Translation non breaking change
Tested by translating and checking the translated string.
=> AST-579 - Search string is not translatable.

.github/dependbot.yml, package.json
Adds dependbot configuration
Adds an npm command `npm run lint:js:fix` to fix all autofixable errors for js linters.
=> Dependbot npm commands

.github/workflows/code-analysis.yml, composer.json, inc/theme-update/astra-update-functions.php, package-lock.json, tests/php/static-analysis-stubs/astra-stubs.php
https://github.com/chekalsky/phpcs-action#php-codesniffer-github-action
I believe we were using this earlier but for some reason changed back to running phpcs command.
=> Use chekalsky/phpcs-action for phpcs as this provides annotations

composer.json, composer.lock
This is published to packagist now - https://packagist.org/packages/brainstormforce/astra-notices
=> Install Astra Notices from packagist.org

Gruntfile.js, package-lock.json, package.json
Does the fix mentioned in https://github.com/brainstormforce/astra/pull/3006#issuecomment-882293773
=> AST-705 - Update NPM dependencies

changelog.txt
=> chore: Changelog updated for v3.6.5

changelog.txt
- Changelog added in next-release which is missing
- Task - https://wp-astra.atlassian.net/browse/AST-537
- Task - https://wp-astra.atlassian.net/browse/AST-579
=> chore: Missing changelog adding in next-release

changelog.txt, inc/addons/transparent-header/classes/dynamic-css/dynamic.css.php, inc/builder/type/header/above-header/dynamic-css/dynamic.css.php, inc/builder/type/header/below-header/dynamic-css/dynamic.css.php, inc/builder/type/header/primary-header/dynamic-css/dynamic.css.php, inc/core/common-functions.php
- Transparent header showing boder in Firefox browser
- Task - https://wp-astra.atlassian.net/browse/AST-711
- Bug fix >
=> AST-711 - Transparent header border showing in firefox even it's not set

README.md, changelog.txt, functions.php, inc/core/class-astra-admin-settings.php, languages/astra.pot, package.json, readme.txt, style.css
=> v3.6.6 release - Ast notice triggers not working

Gruntfile.js, tests/e2e/config/expect-extensions.js, tests/e2e/utils/create-new-user.js
This should hopefully fix the failing e2e tests
=> Clean the Astra build directory before recreating it

inc/extras.php
- While resolving PR comment return value got wrong
- Commit - https://github.com/brainstormforce/astra/pull/3049/commits/e34f1c984d8e2138f83b288895aa8bc3908da77d
- Expected return should be `false` but missed while resolving https://share.bsf.io/5zuNmYe8
- https://share.bsf.io/Apu98nAo
- https://share.bsf.io/9ZuQ2PX1
- With fix - https://share.bsf.io/jku4oPgb
- Bug fix 
- Import starter template having widget designed
=> AST-750 - Return flag corrected which deciding to hide/show widget design options

style.css
=> fix version number not working issue

docs/development/development-workflow.md
Updated the branch from dev to release-candidate
Non breaking changes
=> Updated the branch from dev to release-candidate

changelog.txt, inc/core/class-astra-enqueue-scripts.php
- https://wp-astra.atlassian.net/browse/AST-730
- Move frontend-pro.js file related to addon from theme to add-on
=> AST-730 - imprv: Move frontend-pro.js file related to addon from theme to add-on

inc/assets/css/block-editor-styles-rtl.css, inc/assets/css/block-editor-styles.css, sass/admin/block-editor-styles.scss
- Tag lists overflow & min width updated for improving UI & removing scroll-bar
- Till now - https://share.bsf.io/7KuERAXx
- In PR - https://share.bsf.io/8Lu5J9Yv
- Non-breaking change 
- Check heading tags this main case
- Test overall editor to make sure this not creates any issue on other location in editor
=> AST-777 - Overflow & min-width updated for editor tag lists UI

README.md, assets/fonts/google-fonts.json, changelog.txt, inc/class-astra-dynamic-css.php, inc/core/common-functions.php, inc/customizer/class-astra-customizer.php, inc/extras.php, inc/google-fonts.php, inc/lib/batch-processing/class-astra-wp-background-process.php, inc/theme-update/astra-update-functions.php, inc/theme-update/class-astra-theme-background-updater.php, languages/astra.pot, package-lock.json, package.json, readme.txt, style.css
=> Build: v3.6.9 Release PR

inc/core/class-gutenberg-editor-css.php, inc/core/common-functions.php, inc/dynamic-css/content-background.php, inc/dynamic-css/global-color-palette.php, inc/modules/related-posts/css/dynamic-css.php, inc/theme-update/astra-update-functions.php, inc/theme-update/class-astra-theme-background-updater.php, tests/php/static-analysis-stubs/astra-stubs.php
This has fixes related to static analysis. The suppressed errors will be fixed in https://wp-astra.atlassian.net/browse/AST-877 task.
=> Psalm fix 2

inc/core/common-functions.php, inc/dynamic-css/global-color-palette.php, inc/theme-update/astra-update-functions.php
=> Fixed error related to incorrect parameter type

inc/assets/css/block-editor-styles-rtl.css, inc/assets/css/block-editor-styles.css, sass/admin/block-editor-styles.scss
- On hover block visual experience improved
- PS: Notice hover in screencasts.
- Till now - https://share.bsf.io/Qwu5GyBr
- In this PR - https://share.bsf.io/4gulxLW2
- Non-breaking change 
- Check for normal dropped & with nested blocks
=> AST-762 - Hover block selection improved for GB editor

inc/assets/css/block-editor-styles-rtl.css, inc/assets/css/block-editor-styles.css, sass/admin/block-editor-styles.scss
- Left space is missing for editor pre blocks whereas on frontend it looks correct - https://share.bsf.io/8Lu5Jo0Q
- Same should follow in editor
- Till now - https://share.bsf.io/jku4KPvE
- In PR - https://share.bsf.io/eDuRxy5K
- Till now -  https://share.bsf.io/d5uR0RDz
- In branch -  https://share.bsf.io/2NulBlpp
- Non-breaking change 
- Check above screenshot's pre blocks
- Check them in nested blocks as well
- I tried almost all the blocks in editor but verify once same with all block (if anything I missed)
=> AST-765 - Added editor left spacing for pre blocks for improving editor UI

tests/e2e/config/bootstrap.js
added function to trash all pages before each test
added function
=> trash all pages before each test

README.md, changelog.txt, functions.php, inc/compatibility/class-astra-gutenberg.php, package-lock.json, package.json, readme.txt, style.css, tests/php/static-analysis-stubs/astra-stubs.php
---
---
Fixes the Gutenberg Group block full width issue when theme.json is added.
Before - [https://share.bsf.io/5zuNbnnk](https://share.bsf.io/5zuNbnnk)
After    - [https://share.bsf.io/E0ujmog4](https://share.bsf.io/E0ujmog4)
Test on local/websitedemos - https://websitedemos.net/portfolio-08/
=> Build: Release PR Fix: Group block full width fix

changelog.txt
- Updated changelog point for PHPCS NamingConvention task
=> AST-908 - Updated PHPCS NamingConvention changelog points

inc/builder/type/header/mode-switcher/class-astra-header-mode-switcher-loader.php, inc/builder/type/header/woo-cart/dynamic-css/dynamic.css.php, inc/core/builder/class-astra-builder-options.php
- Commit - https://github.com/brainstormforce/astra/pull/3695/commits/30696f6d416aab4bf7411577993fb648e257b646
- As wp_head action still creates jerk, now checking this issue if resolves with wp action
=> chore: action chnaged to check dark mode jerk render issue

inc/core/class-astra-enqueue-scripts.php
- Ref PR -
- https://github.com/brainstormforce/astra/pull/3469/files
- https://share.bsf.io/JrunQrxL
- Bug fix
=> AST-1026 - - fix: astra_cart undefined error fixed in customizer

tests/e2e/specs/customizer/header-builder/header-types/mobile-header/off-canvas-menu/spacing.test.js
Header builder → Off canvas → off canvas menu → Design → Spacing option
https://share.getcloudapp.com/E0ug450w
npm run test:e2e:interactive -- tests/e2e/specs/customizer/header-builder/header-types/mobile-header/off-canvas-menu/spacing.test.js
=> QAE-296 - E2E test case for off canvas menu spacing option

tests/e2e/specs/customizer/blog/single-post/grid-columns-layout.test.js
Added Test case for Blog/archive grid columns and layout option
https://share.getcloudapp.com/WnuqKXXO
Run single test : npm run test:e2e:interactive tests/e2e/specs/customizer/blog/single-post/grid-columns-layout.test.js
=> QAE-302 - E2E Test case for Single post grid columns and layout option

tests/e2e/specs/customizer/header-builder/transparent-header/social-icon-text-background-color.test.js, tests/e2e/specs/customizer/header-builder/transparent-header/social-icon-text-bg-color-search-color.test.js
Header-builder → Transparent Header → Design → Social icon and background color, Search icon color
https://share.getcloudapp.com/E0ugLgWP
How To test ?: npm run test:e2e:interactive -- tests/e2e/specs/customizer/header-builder/transparent-header/social-icon-text-bg-color-search-color.test.js
=> QAE-881 - E2E test case for transparent header social icon text and background color, Search icon color

README.md, changelog.txt, functions.php, inc/class-astra-dynamic-css.php, inc/compatibility/class-astra-gutenberg.php, inc/core/class-astra-wp-editor-css.php, inc/dynamic-css/container-layouts.php, inc/theme-update/astra-builder-migration-updater.php, inc/theme-update/astra-update-functions.php, languages/astra.pot, package.json, readme.txt, style.css, tests/php/static-analysis-stubs/astra-stubs.php
=> AST-1926 - Build: Release PR

README.md, functions.php, languages/astra.pot, package-lock.json, package.json, readme.txt, style.css
=> AST-1931 - Build: Release PR

inc/theme-update/class-astra-theme-background-updater.php
Moved update function to proper version array
Checked by running updater by moving from master to current latest branch
=> Refactor : Moved updater function into new version number array

inc/assets/js/block-editor-script.js
showing on customizer when updating woocommerce settings.
https://share.bsf.io/8Lu09Bgr
=> AST-1934 - Woocommerce customizer showing console error

inc/assets/css/ast-builder-customizer-rtl.css, inc/assets/css/ast-builder-customizer.css, inc/compatibility/woocommerce/customizer/class-astra-customizer-register-woo-section.php, inc/compatibility/woocommerce/customizer/sections/layout/class-astra-woo-shop-layout-configs.php
Before: https://share.bsf.io/NQuljb4x 
After: https://share.bsf.io/7Ku6kvwL
=> AST-1955 - Moved the shop skin layout options under the Product catalog

README.md, assets/fonts/google-fonts.json, changelog.txt, functions.php, inc/builder/controllers/class-astra-builder-ui-controller.php, inc/builder/type/header/woo-cart/dynamic-css/dynamic.css.php, inc/class-astra-global-palette.php, inc/compatibility/woocommerce/class-astra-woocommerce.php, inc/compatibility/woocommerce/customizer/sections/class-astra-woo-store-notice-configs.php, inc/google-fonts.php, inc/markup-extras.php, inc/theme-update/astra-update-functions.php, inc/theme-update/class-astra-theme-background-updater.php, languages/astra.pot, package-lock.json, package.json, readme.txt, style.css, tests/php/static-analysis-stubs/astra-stubs.php
=> AST-1934 - Build: Release PR

inc/core/common-functions.php
Jira : https://brainstormforce.atlassian.net/browse/AST-2186
https://d.pr/i/xSi01d
New feature (non-breaking change which adds functionality) 
Checked links from upgrade to astra pro button
=> AST-2186 - Url encoding issue for customizer url

README.md, assets/fonts/google-fonts.json, changelog.txt, composer.lock, inc/compatibility/woocommerce/class-astra-woocommerce.php, inc/compatibility/woocommerce/customizer/sections/layout/class-astra-woo-shop-misc-layout-configs.php, inc/compatibility/woocommerce/woocommerce-common-functions.php, inc/core/class-astra-admin-settings.php, inc/core/common-functions.php, inc/extras.php, inc/google-fonts.php, inc/theme-update/astra-update-functions.php, languages/astra.pot, package-lock.json, package.json, readme.txt, style.css, tests/php/static-analysis-stubs/astra-stubs.php
=> AST-2137 - Release PR v3.9.2

inc/builder/controllers/class-astra-builder-ui-controller.php
=> code formatting

inc/core/class-gutenberg-editor-css.php
Fix: Visibility icon alignment issue with page title on specific templates (older ones).
https://d.pr/i/wR5xsk
Fix: Visibility icon alignment issue with page title on specific templates (older ones).
- Choose Party Planner Template (Older template).
- Create a page using gutenberg.
- You will observe that visibility icon (eye icon) is broken.
- It needs to be aligned well with page title.
=> AST-2230 - fix: visibility icon alignment issue

changelog.txt, inc/modules/related-posts/css/static-css.php
Jira : https://brainstormforce.atlassian.net/browse/AST-2269
https://d.pr/L055Wp
- Checked in frontend and customizer preview.
- Checked with various container types
=> AST-2269 - Remove related post border 

changelog.txt, inc/core/class-astra-theme-options.php, inc/core/common-functions.php, inc/theme-update/astra-update-functions.php, inc/theme-update/class-astra-theme-background-updater.php, tests/php/static-analysis-stubs/astra-stubs.php
Jira : https://brainstormforce.atlassian.net/browse/AST-2268
https://d.pr/i/LABXJk
Improvement
- Checked by resetting theme
- Checked in frontend
=> AST-2268 - Removed sidebar from default layout while fresh install

changelog.txt, inc/class-astra-dynamic-css.php, inc/core/class-astra-theme-options.php, inc/customizer/configurations/typography/class-astra-body-typo-configs.php, inc/theme-update/astra-update-functions.php
Reverts brainstormforce/astra#4662
- As this feature will improvise in better way in next update, so reverting the PR.
=> AST-2270 - Revert "AST-2270 - remove input dotted focus"

README.md, assets/fonts/google-fonts.json, changelog.txt, functions.php, inc/class-astra-dynamic-css.php, inc/google-fonts.php, languages/astra.pot, package-lock.json, package.json, readme.txt, style.css
=> AST-2332 - Build release PR v3.9.3

inc/class-astra-dynamic-css.php, inc/core/class-astra-enqueue-scripts.php, inc/customizer/configurations/layout/class-astra-blog-layout-configs.php, inc/customizer/configurations/layout/class-astra-blog-single-layout-configs.php, inc/customizer/configurations/layout/class-astra-sidebar-layout-configs.php, inc/customizer/configurations/layout/class-astra-site-container-layout-configs.php, inc/markup-extras.php
=> Narrow width container global, archive, single post, page

inc/class-astra-dynamic-css.php, inc/core/common-functions.php, inc/customizer/configurations/layout/class-astra-blog-layout-configs.php, inc/customizer/configurations/layout/class-astra-blog-single-layout-configs.php
Reduced code footprint and fixed default width toggle
Improvements / refactor
=> Narrow container function

admin/assets/build/dashboard-app.asset.php, admin/assets/build/dashboard-app.css, admin/assets/build/dashboard-app.js, admin/assets/src/dashboard-app/MainNav.js, admin/assets/src/dashboard-app/pages/custom-layouts/CustomLayouts.js, admin/assets/src/dashboard-app/pages/starter-templates/StarterTemplates.js, admin/assets/src/dashboard-app/pages/welcome/ExtensionCard.js, admin/includes/class-astra-menu.php
AST-2253 Fixed admin dashboard redesign issues with layouts
=> AST-2253 Fixed admin dashboard redesign issues with layouts

admin/assets/build/dashboard-app.asset.php, admin/assets/build/dashboard-app.css, admin/assets/build/dashboard-app.js, admin/assets/src/dashboard-app/pages/welcome/VideoPopup.js
Fixed minor video popup issues on Astra welcome screen
=> Fixed minor video popup issues on Astra welcome screen

.github/workflows/code-analysis.yml
Increased memory limit for phpcs on github
- 
- 
-
=> AST-2531 - Increased code analysis memory

admin/assets/build/dashboard-app-rtl.css, admin/assets/build/dashboard-app.asset.php, admin/assets/build/dashboard-app.css, admin/assets/build/dashboard-app.js, admin/assets/src/common/common.scss, admin/assets/src/dashboard-app/MainNav.js, admin/assets/src/dashboard-app/pages/docs/Docs.js, admin/assets/src/dashboard-app/pages/docs/UpgradeToPro.js, admin/assets/src/dashboard-app/pages/welcome/ExtensionCard.js, admin/assets/src/dashboard-app/pages/welcome/Welcome.js, inc/addons/heading-colors/class-astra-heading-colors-loader.php, inc/core/builder/class-astra-builder-options.php, inc/core/class-astra-theme-options.php, inc/modules/related-posts/class-astra-related-posts-loader.php
Fixed qa comments for default color and typo
=> Fixed qa comments for default color and typo

inc/core/builder/class-astra-builder-options.php, inc/customizer/configurations/builder/header/class-astra-mobile-menu-component-configs.php
- Defaults updated for mobile menu
=> AST-2736 - Defaults updated for mobile menu

changelog.txt
- Changelog updated for release 4.0
- New feature (non-breaking change)
=> AST-2812 - Changelog update for 4.0

inc/core/builder/class-astra-builder-options.php
AST-2848 - Fixed footer bg defaults with border
=> AST-2848 - Fixed footer bg defaults with border

assets/fonts/google-fonts.json, changelog.txt, inc/google-fonts.php, languages/astra.pot, package-lock.json
=> AST-2849 - 4.0 Release Build

README.md, admin/includes/class-astra-menu.php, changelog.txt, functions.php, languages/astra.pot, package.json, readme.txt, style.css
=> AST-2854 - Release checklist PR

changelog.txt, inc/compatibility/class-astra-starter-content.php
Jira : https://brainstormforce.atlassian.net/browse/AST-2875
https://d.pr/5sr5F5
- Checked by fresh installing astra and applying starter content settings from customizer.
=> AST-2875 - Starter content changing site title

changelog.txt, inc/compatibility/class-astra-starter-content.php
Jira : https://brainstormforce.atlassian.net/browse/AST-2862
- 
-
=> AST-2862 - Theme preview not displaying properly on wordpress.org preview

inc/class-astra-dynamic-css.php
jira : https://brainstormforce.atlassian.net/browse/AST-3004
https://d.pr/v/9CkebH
- Checked in responsive menu
=> AST-3004 - For toggle button accessibility global color is not working

changelog.txt, inc/markup-extras.php
**Test Data**: After installing BBpress the author bio page showing multiple time check screenshot for more details. 
All is explained in this video: https://share.getcloudapp.com/p9uLY1Zr 
**Any Other details:** 
https://secure.helpscout.net/conversation/2129150514/296764?folderId=4660463
https://secure.helpscout.net/conversation/2140044270/302332
=> AST-2944 - fix: BBPress Compatibility with Astra Theme

inc/builder/type/header/off-canvas/dynamic-css/dynamic.css.php
Revert PR - https://github.com/brainstormforce/astra/pull/5034
=> AST-2717 - Revert menu toggle issue .

changelog.txt, inc/core/builder/class-astra-builder-helper.php, inc/core/class-astra-icons.php, inc/core/common-functions.php, inc/extras.php
Resolving PHP8.1 incompatibility issue.
- https://d.pr/v/V2ikO7
```
[25-Apr-2023 14:31:11 UTC] PHP Deprecated:  Automatic conversion of false to array is deprecated in /Users/vrunda1/Local Sites/ai/app/public/wp-content/themes/astra/inc/core/class-astra-icons.php on line 38
[25-Apr-2023 14:31:11 UTC] PHP Deprecated:  Automatic conversion of false to array is deprecated in /Users/vrunda1/Local Sites/ai/app/public/wp-content/themes/astra/inc/core/class-astra-icons.php on line 38
[25-Apr-2023 14:31:11 UTC] PHP Deprecated:  Automatic conversion of false to array is deprecated in /Users/vrunda1/Local Sites/ai/app/public/wp-content/themes/astra/inc/core/builder/class-astra-builder-helper.php on line 1177
[25-Apr-2023 14:31:11 UTC] PHP Deprecated:  Automatic conversion of false to array is …
```
=> AST-2914 - Fix:Incompatibility with PHP 8.1 errors.

package-lock.json, package.json
Reverts brainstormforce/astra#5214
=> Revert "chore(deps-dev): bump @wordpress/api-fetch from 6.26.0 to 6.34.0"

changelog.txt, inc/markup-extras.php
BBPress widgets running in infinite loop.
JIRA: [https://brainstormforce.atlassian.net/browse/AST-3238](https://brainstormforce.atlassian.net/browse/AST-3238)
**BEFORE**: [https://d.pr/i/gVhPfU](https://d.pr/i/gVhPfU)
**AFTER**: [https://d.pr/i/JEb3Be](https://d.pr/i/JEb3Be)
Updated condition to not run infinite loop for widgets rendering
=> AST-3238 - BBPress widget loading issue

inc/assets/js/block-editor-script.js
- Title meta option throwing JS error of undefined
- https://d.pr/i/SwN8oU
- Bug fix 
- There should not be any JS error
=> AST-3409 - Undefined JS error for block editor meta while handling title visibility control

inc/customizer/extend-custom-controls/build/index.asset.php, inc/customizer/extend-custom-controls/package-lock.json, inc/customizer/extend-custom-controls/src/common/astra-color-picker-control.js
Description: BG responsive control not working in 6.3
User setting file - [2rweb.json](https://d.pr/f/L6CcBa)
Steps To Replicate - 
1. Import provide setting file
2. Go To customizer → Header Builder → Primary Header → Design Section
3. Open the Console to notice the error 
4. Click on the background image - it will disappear the entire section and some console error.
- https://d.pr/v/5paf7x
- Bug Fix - Non breaking changes.
=> AST-3446 - Fix: Gradient picker breaking in BG responsive control section.

SECURITY.md
- Added new SECURITY.md file for security udpates & their policies
=> chore: SECURITY.md file with policy & details

changelog.txt, inc/customizer/configurations/typography/class-astra-archive-typo-configs.php, inc/lib/astra-notices/class-astra-notices.php
[Task](https://brainstormforce.atlassian.net/browse/AST-3427)
Non-Breaking bug fixes
=> AST-3427 - Issue with Astra Pro Deactivated Modules Causing Blank Design Page

changelog.txt, inc/customizer/configurations/builder/class-astra-builder-base-configuration.php
1. This Separator is not required - https://d.pr/i/T5O5BD
2. Incorrect top spacing - [Annotation-Annotation on 2023-10-09 at 15-56-54.png.png](https://d.pr/i/pe9aOf)
3. JIRA - https://brainstormforce.atlassian.net/browse/AST-3550
Included in Description
Bug Fixes
- Extra Separator should be removed.
- Incorrect top spacing fixed.
=> AST-3550 - Header Footer Widget Design Section Issues

inc/class-astra-dynamic-css.php
Double header causing high CLS issue
[Task](https://brainstormforce.atlassian.net/browse/AST-3568)
Breakung Changes
=> AST-3568 - Double header causing CLS issue.

inc/assets/js/customizer-preview.js, inc/class-astra-dynamic-css.php, inc/core/class-astra-theme-options.php, inc/customizer/configurations/layout/class-astra-blog-layout-configs.php
Jira : https://brainstormforce.atlassian.net/browse/AST-3514
https://d.pr/v/jUSN5L 
- Checked with customizer preview and in frontend
=> AST-3514 - Featured image hover effects

inc/modules/posts-structures/customizer/class-astra-posts-archive-structures-configs.php
Jira : https://brainstormforce.atlassian.net/browse/AST-3579
https://d.pr/v/FEU5Xj
New feature (non-breaking change which adds functionality) 
Checked if it works with all layouts ( layout 1 to 6 ) 
Checked with post filters
Checked with different types of pagination ( Scroll, paginate etc )
Checked responsive 
Checked on blog category and tag pages 
Checked with wocommerce and all woocommerce layouts
Checked with custom post type
=> AST-3579 - Post reveal effect 

changelog.txt, inc/assets/js/block-editor-script.js
- JIRA - https://brainstormforce.atlassian.net/browse/AST-3621
https://d.pr/v/yiiPsH
1. Install Spectra.
2. Install Astra Latest.
3. Install Astra Pro.
4. Visit the Editor for a Post/Page.
5. Add different types of Spectra / Gutenberg blocks.
6. Check if the editor is loading super slow.
=> AST-3621 - Optimization for Slow Editor due to Page Background Live Previews Features.

changelog.txt, functions.php, inc/class-astra-dynamic-css.php, inc/theme-update/astra-update-functions.php, inc/theme-update/class-astra-theme-background-updater.php
Reverts brainstormforce/astra#5576
=> AST-3350 - Revert "AST-3350 - Improvement: Forms default stylings improved."

.github/actions/spelling/allow.txt, inc/class-astra-dynamic-css.php, inc/compatibility/class-astra-gravity-forms.php
- Fix: Dropdown issue resolved.
- Improvement: Compatibility with Gravity Forms.
- Refactor: Accessibility conditions optimized & reduced LOC.
https://bsf.d.pr/i/Zarmux
Improvements & bug-fixes
- Test Gravity Forms dropdown issue.
- Test Gravity Forms Accessibility.
=> AST-3729 - Improvement: Compatibility with Gravity Forms.

admin/class-astra-admin-loader.php, changelog.txt
[Task](https://brainstormforce.atlassian.net/browse/AST-2903)
[GitHub issue](https://github.com/brainstormforce/astra/issues/4956)
=> AST-2903 - Improv: Check for Class Exists in class-astra-admin-loader.php

changelog.txt, inc/metabox/class-astra-meta-boxes.php
**Description**: Astra meta settings showing for beaver builder themer layout, which is not correct we need to remove that
**Screenshot**: https://d.pr/i/qHoVpK , https://bsf.d.pr/i/0TEQDa 
- Condition twiks - Non breaking changes
- Test cases mention in [task](https://brainstormforce.atlassian.net/browse/AST-3732)
=> AST-3732 - Fix - Astra meta settings showing for beaver builder themer layout. 

changelog.txt, inc/assets/js/column-block-compatibility.js, inc/class-astra-dynamic-css.php, inc/compatibility/woocommerce/class-astra-woocommerce.php, inc/core/class-astra-wp-editor-css.php
- UI fixes for cart & checkout Woo blocks
- https://d.pr/v/hAr6wa
- Bug fix 
- All the test cases added in card
=> AST-3773 - Fix: Design tweaks for cart & checkout Woo blocks
