- inc/core/common-functions.php
Function `ast_the_archive_title()` is not used in the theme. So, It is removed.
> Removed unused functions

- inc/customizer/class-ast-customizer.php
Simplified the `SCRIPT_DEBUG` logic for the customizer assets (CSS & JS) files.
> Customizer asset SCRIPT_DEBUG support

- inc/class-astra-dynamic-css.php
Issue : Typography doesn't  apply to site-title span tag.
Fix : Added css for site-title class.
> Site title typography fix when heading tag not applied

- inc/blog/single-blog.php
- inc/core/deprecated/deprecated-filters.php
Issue : Deprecate `astra_sigle_post_navigation_enabled` filter
Fix : `astra_sigle_post_navigation_enabled` filter deprecated. Added `astra_single_post_navigation_enabled` filter added
> Deprecated astra_sigle_post_navigation_enabled filter.

- inc/theme-update/class-astra-theme-update.php
Issue : Fresh installation executing backward compatibility functions.
Fix : Current version assigned when empty.
> Current version store issue fixed

- assets/js/unminified/customizer-preview.js
- inc/class-astra-dynamic-css.php
- inc/extras.php
This keeps the CSS weight of the new CSS low so that anyone who has added any custom CSS solution will keep overriding this new CSS
> Fix: add width to the svg logo's so that they are visible.

- inc/extras.php
Issue : Featured image note working on static blog page
Fixed : arguments changed in "astra_get_post_thumbnail" function
> Featured image issue fixed

- inc/compatibility/class-astra-beaver-builder.php
- inc/compatibility/class-astra-elementor.php
Astra automatically sets up page meta options for layout when using a page builder. This helps to reduce the number of clicks when setting up a new page.
Although if someone wants to disable this functionality. `astra_enable_page_builder_compatibility` filter can be used.
eg - 
```
add_filter( 'astra_enable_page_builder_compatibility', '__return_false' );
```
> New filter to enable / disable automatic page builder compatibility.

- inc/extras.php
It was displayed after the preview was reloaded.
> Fix: SVG logo not displayed in customiser when initially addding.

- changelog.txt
- functions.php
- languages/astra.pot
- package.json
- style.css
**v1.0.31**
New: Filter `astra_enable_page_builder_compatibility` added to disable default page builder compatibility meta settings.
Fixed: Some SVG logos being not displayed.
Fixed: Thumbnail image not visible on a blog page.
> Version 1.0.31

- changelog.txt
- inc/core/deprecated/deprecated-filters.php
- Fixed: Deprecated filter fatal error in WordPress 4.5 & below.
> Astra filters deprecated

- inc/compatibility/woocommerce/class-astra-woocommerce.php
- style.css
This happens when Astra shortcode for the mini cart is used on a page.
> Fix: fatal error in page builder modes 

- functions.php
Beaver Themer compatibility requires a anonymous function which was introduced only in PHP5.3 so this causes fatal error on older PHP versions.
> Load Themer compatibility only if PHP >=5.3

- inc/compatibility/lifterlms/class-astra-lifterlms.php
Remove the hooked `astra_single_post_navigation_markup()` for LifterLMS quizzes.
It's pretty clear that this kind of navigation is intended for blog posts (and maybe pages) but causes a poor user experience when displayed on quizzes.
> remove post nav on LifterLMS quizzes

- assets/css/unminified/editor-style-rtl.css
- assets/css/unminified/editor-style.css
- assets/css/unminified/style-rtl.css
- assets/css/unminified/style.css
- inc/class-astra-after-setup-theme.php
- inc/extras.php
- sass/site/media/_galleries.scss
- Fixed black bars when the video is made full width using the `ast-oembed-container` class
- Allow the `oembed` container class to pass through the filter `oembed_result` so that videos added through `wp_oembed_get()` will also get the wrapper.
- Introduces filter `astra_allowed_fullwidth_oembed_providers ` of providers to be made full width.
> Fixes issues related to video embeds due to ast-oembed-container class

- inc/compatibility/lifterlms/class-astra-lifterlms.php
This adds Astra layout post options to LifterLMS quizzes via the [course builder theme compatibility API](https://lifterlms.com/docs/quiz-theme-compatibility-developers/).
This allows users to select alternate layout options on LifterLMS quizzes via the builder.
Currently we only have support for a single field so possibly we could add support for the sidebar fields (as well as many of the other layout/post options available in Astra. However, at this moment I wanted to make this available to you if you were interested in using it.
<3
> add LifterLMS course builder layout option compatibility

- inc/compatibility/woocommerce/class-astra-woocommerce.php
- inc/compatibility/woocommerce/woocommerce-common-functions.php
- Fixed: WooCommerce composite products plugin conflict on Single Product Page.
> Remove Single product cart form wrapper

- inc/compatibility/class-astra-elementor-pro.php
Fix: check if Elementor pro's method actually exists before loading the compatibility class
> Fix fatal error when older version of Elementor Pro is installed

- inc/customizer/class-astra-font-families.php
- inc/customizer/custom-controls/typography/typography.js
This needs to be tested with the [Custom Fonts](https://wordpress.org/plugins/custom-fonts/) plugin.
What happens if the font name has `'` or `,` in it.
Fixes #512
> Fix: weights for google fonts not displayed in the list

- inc/compatibility/lifterlms/class-astra-lifterlms.php
In an effort to make it simpler for themes to integrate with LifterLMS we're moving towards a single declaration of theme support.
This declares Astra as supporting LifterLMS because you do actually support LifterLMS very well!
After this I will stop spamming with PRs (at least for a few weeks).
Thanks as always
> add official lifterlms theme support

- inc/compatibility/lifterlms/class-astra-lifterlms.php
Like #476 this removes post nav from "Assignments" which are available via the LifterLMS Assignments add-on.
This was reported to me as a bug in LifterLMS today and I'd rather have this fixed in Astra core if you're okay with it instead of providing custom code snippets or CSS hacks when this is reported to us as a bug
Thanks as always!
> remove post navigation from LifterLMS Assignments single posts

- changelog.txt
- inc/customizer/class-astra-customizer.php
when function wp_generate_attachment_metadata() does not exist.
> Include 'wp-admin/includes/image.php' file

- inc/compatibility/woocommerce/class-astra-woocommerce.php
```
Warning: Invalid argument supplied for foreach() in /<path-to-site>/plugins/learndash-woocommerce/learndash_woocommerce.php on line 316
```
Support ticket #88059
> Fix: PHP warning when using LearnDash WooCommerce addon.

- inc/theme-update/class-astra-pb-compatibility.php
- inc/theme-update/class-astra-theme-update.php
Strictly check if version number is not set when updating the saved version number.
> Delay migrating astra settings on theme version update until action wp

- inc/extras.php
Default thumbnail size being pulled for blog archives when set to full results in image size penalties on Google pagespeed for archive pages (below 40%)
For a short term fix the thumbnail size being fetched in "function astra_get_post_thumbnail" was set to large to reach a balance between pagespeed ranking and image quality of post thumbnail being displayed on archive pages.
> Change default thumbnail size

- inc/class-astra-dynamic-css.php
For sites migrating to this version will have this disabled by default.
> Fix: for fresh sites submenu should open below the header

- inc/class-astra-dynamic-css.php
fix: megamenu full width border color inherit issue
> fix: megamenu full width border color inherit issue

- changelog.txt
- Fix: Block Editor - Background color from content does not work.
- Fix: Block Editor - Columns block having incorrect margin when on tablet/mobile devices.
- Fix: Removed padding to column element of Gutenberg for responsive devices.
- Fix: Menu not correctly centers aligned when no menu is set to the primary location, i.e. wp_page_menu().
- Fix: Search is not visible on screen sizes 768px to 920px.
- Fix: Background color does not work for Below Header.
- Fix: Removed top border for custom menu item on mobile devices.
- Fix: LifterLMS - add LifterLMS lesson page builder support (props - @thomasplevy)
> Update changelog for v1.6.3

- inc/assets/css/block-editor-styles-rtl.css
- inc/assets/css/block-editor-styles.css
- inc/core/class-gutenberg-editor-css.php
- sass/admin/block-editor-styles.scss
The block editor adds a negative margin of -28px on left and right for  This negative margin is removed and added to the content width that is added to the containers in the block editor.
> Fix: Gutenberg content width same as the frontend

- inc/customizer/class-astra-customizer.php
This will allow the logo to be correctly replaced with the full dimension of the image file in the frontend
> Fix: Regenerate the logo if filter astra_resize_logo is enabled 

- changelog.txt
- functions.php
- inc/extras.php
- languages/astra.pot
- package-lock.json
- package.json
- style.css
- New: filter to disable automatic logo resizing. (https://wpastra.com/docs/disable-logo-cropping/)
- New: CSS class `ast-left-align-sub-menu` will change the direction navigation menu opens for all submenus. (https://wpastra.com/docs/change-the-direction-for-submenu-opening/)
- Improvement: Gutenberg - Body color not applied in the block editor when boxed layout or contained boxed layout.
- Improvement: Correctly move hook `astra_head_bottom` to the very bottom of the <head> tag.
> Version 1.6.10

- inc/core/class-astra-admin-settings.php
- inc/lib/notices/class-astra-notices.php
[Fix] -> Add New theme upload theme was not working because of the plugin-install JS enqueue.  To fix this issue, added a condition to load plugin-install JS only when notice is active.
> Upload theme not working fix

- inc/compatibility/class-astra-amp.php
I noticed quite a few AMP validation errors when testing the theme, and they turned out to just be due to `<amp-state>` being incorrectly placed in the `head` when it has to be in the `body`.
Also, these attributes on `<amp-state>` are added automatically by the `amp-state` component and they should be omitted:
* `class="i-amphtml-element i-amphtml-layout-container"`
* `hidden=""` 
* `aria-hidden="true"`
> AMP Compatibility: Fix usage of amp-state component

- inc/extras.php
To fix this issue, added one more condition to check if title meta is active do not add 
`ast-header-without-markup` class.
> Fix: Title margin appearing when only title is globally enabled.

- inc/class-astra-dynamic-css.php
- inc/core/class-gutenberg-editor-css.php
Fixed: Color for anchor tag is not working in Gutenberg blockquote in front end and back end.
> Fixed: color for anchor is not working in blockquote in gutenberg

- inc/addons/transparent-header/classes/dynamic-css/dynamic.css.php
Fix: Transparent header BG color is not inherited to iPad and mobile
> Fix: Transparent header BG color is not inherited to iPad and mobile

- header.php
- inc/blog/blog-config.php
- inc/blog/single-blog.php
- It only focuses on markup with schema attributes so that these can be disabled from the child theme.
> Use astra_attr to build markup

- inc/compatibility/woocommerce/class-astra-woocommerce.php
[Fix] -> Pagination not appearing ( all products are loading on load )  for Products in Subcategory archive pages.
> Fix: Infinite Scroll not working on WooCommerce Subcategory pages.

- inc/core/class-astra-enqueue-scripts.php
Updated to the latest version of the Astra theme and encountered an AMP validation error (see attachment) 
This validation error can be fixed by preventing the printing of the `skip-focus-fix` script, since it is covered by the AMP framework.
See: https://github.com/ampproject/amphtml/issues/18671
> fix: Omit printing skip-focus-fix script on AMP content

- inc/compatibility/class-astra-amp.php
- inc/core/class-astra-enqueue-scripts.php
- inc/core/common-functions.php
- inc/core/deprecated/deprecated-functions.php
- inc/extras.php
- to fix the typo in the function name.
- deprecates `astra_is_emp_endpoint()` function.
> fix: rename function astra_is_emp_endpoint to astra_is_amp_endpoint

- inc/cache/class-astra-cache-base.php
- Avoid PHP notices in the admin area on custom admin pages.
> Fix: don't set Astra_Cache in admin

- inc/core/class-astra-admin-settings.php
- fix: Plugin install / Thick box JS added in the Astra Options p age for the "details >>" popup and loading these JS files on only Astra Options page which resolves the Upload Theme button issue.
--
> fix: Upload Theme button not working.

- inc/addons/breadcrumbs/class-astra-breadcrumb-trail.php
- inc/addons/breadcrumbs/class-astra-breadcrumbs.php
- inc/addons/breadcrumbs/customizer/class-astra-breadcrumbs-configs.php
- inc/addons/breadcrumbs/dynamic-css/dynamic.css.php
The Breadcrumb source option went missing after the Yoast SEO v12.8.1.
> fix: Added compatibility for Yoast SEO v12.8.1

- inc/class-astra-dynamic-css.php
The URL space used to get added in the Astra woff font URL This caused issues with plugins like Fast Velocity Minify.
>  fix: Removed space in font URL

- inc/assets/css/astra-admin-menu-settings.css
- inc/customizer/custom-controls/color/class-astra-control-color.php
- inc/customizer/custom-controls/responsive-color/class-astra-control-responsive-color.php
- RGB color format not working in ast-color, ast-responsive-color params
- Added CSS for this - https://share.getcloudapp.com/yAuvxQ1e
- Thems does not have CSS for Extended Plugins activate status
> fix: RGBA color format not working

- inc/compatibility/class-astra-amp.php
- Replaced li and a tags with .menu-item and .menu-link
> fix: CSS tag fixes in AMP-Astra

- inc/extras.php
We changed how the "Add-ons" link can be modified in GiveWP 2.6.0 using a filter. Right now if you're running Astra and GiveWP 2.6.0+ you'll see two "Add-ons" links in the dashboard menu. This PR updates that so now only the single link appears with the proper affiliate link.
> fix: givewp referral link so two "Add-ons" pages don't display in GiveWP 2.6.0+

- inc/compatibility/class-astra-amp.php
- From theme version 2.4.2 AMP toggle before icon breaks
- https://share.getcloudapp.com/geuWd46E
- https://share.getcloudapp.com/L1u7Wd5p
- Updated CSS entity for this AMP toggle before the button
- Test from master to this branch
- My code is tested
- My code passes the PHPCS tests
- My code follows accessibility standards 
- I've included any necessary tests
- I've added proper labels to this pull request
> fix: AMP CSS toggle before entity breaks in 2.4.2

- inc/core/common-functions.php
PHP 7.4 noitce for function `hexdec`
https://share.getcloudapp.com/o0ugO97A
Added condition to check if the provided string is hex or not. If not return the string without passing it through `hexdec`
Switched the branch and all the PHP notices were gone.
> fix: PHP 7.4 notices.

- inc/class-astra-dynamic-css.php
- inc/core/class-gutenberg-editor-css.php
Gutenberg image wide width issue fixed and removed the unused CSS.
Box content -- full width image
https://share.getcloudapp.com/mXuBWb7k
Box-content -- wide width image
https://share.getcloudapp.com/mXuBWbqB
Bug-fix.
( Image wide width changes should reflect in the editor ) 
Checked the fill width and wide width image width options with content boxed layout.
> fix: removed the unnecessary CSS in the code.

- inc/core/common-functions.php
- Toggle Button Color breaks when RGBA color applied
- Same color code applies to color & BG-color
- https://share.getcloudapp.com/GGuk1YBe
- https://share.getcloudapp.com/xQuWXrkP
- Previously we added ctype_xdigit check to resolve issues in PHP 7.4
- Checked the color code type & if its rgba code then respective hex code returned
- Tested by setting the color to Toggle Button Color
- My code is tested
- My code passes the PHPCS tests
- My code follows accessibility standards
- I've included any necessary tests
- I've added proper labels to this pull request
> fix: astra_get_foreground_color returned same rgba color code instead of hex code

- inc/compatibility/class-astra-elementor.php
- In v2.9.9 Elementor has removed [ .elementor-widget-heading .elementor-heading-title { margin: 0 } ] CSS.
- Again in v2.9.10 Elementor added this as .elementor-heading-title { margin: 0 } but still our [ .entry-content heading { margin-bottom: 20px } ] CSS overrding their fix.
- That's why we are adding this CSS fix to headings by setting bottom-margin to 0.
- https://share.getcloudapp.com/RBuq5PqW
- https://share.getcloudapp.com/6qu2K05A
- Added short CSS to set bottom-margin as 0
- With ELementor v2.9.8
- With Elementor v2.9.10
- My code is tested
- My code passes the PHPCS tests
- My code follows accessibility standards
- My code has proper inline documentation 
- I've included any necessary tests
- I've added proper labels to this pull request
> fix: Elementor headings directly applied bottom margin 20px from v2.9.9

- inc/compatibility/class-astra-elementor.php
- Moved Elementor headings compatibility margin CSS into dynamic styles.
- So it only loads once (previously it load twice because of two different actions)
- https://share.getcloudapp.com/ApuA9G0v
- Removed `elementor/preview/enqueue_styles` & `elementor/frontend/after_enqueue_styles` actions 
- Loaded CSS on `astra_dynamic_theme_css` filter
- With new version of Elementor
- Page source to verify it should not load twice.
- Dynamic styles for headings should apply from Elementor builder
- This our CSS should not restrict dynamic CSS coming from the builder
> chore: Elementor headings compatibility CSS loads twice

- inc/class-astra-dynamic-css.php
- inc/customizer/configurations/colors-background/class-astra-footer-colors-configs.php
- inc/markup-extras.php
- Added filter to add menu-link class to menu anchors
- Replaced missed anchor tag with menu-link selector
- https://i.imgur.com/2m8x4HD.png
- Used the filters to load the styles based on this selector
- By deactivating Addon
- With normal WP Nav & Page menu
> fix: Updations in Astra headers PR as per Support & QA points

- inc/extras.php
- Upgrade affiliate link has been updated for WPForms
- https://share.getcloudapp.com/GGuoYBby
- Used their URL param for landing users to the actual sales page
- With the link
> chore: WPForms upgrade affiliate link

- inc/core/class-gutenberg-editor-css.php
Fixed a warning displayed in the editor view in case if the woocommerce plugin is disabled.
Non-breaking change which fixes an issue
Checked by activating woocommerce and then visiting the editor view and similarly deactivating and checking the editor's view.
>  fix: added is_callable check for astra_woocommerce class.

- functions.php
- inc/core/class-astra-theme-options.php
- inc/theme-update/astra-update-functions.php
- inc/theme-update/class-astra-theme-background-updater.php
Changed the option name of the footer widget background widget from 'footer-adv-bg-obj-responsive' to 'footer-adv-bg-obj'.
Checked the working of the footer widget background-color as well as background image.
> fix: footer wigets background color option not working after update.

- inc/extras.php
- inc/markup-extras.php
1. Added prefix astra_remove_controls to function remove_controls.
2. escaped attribute for arai-label for slide search form.
Non-breaking changes.
Tested on code level that the existing and new code is working properly.
> fix: function prefix and making attr translatable for Slide Search.

- changelog.txt
- inc/customizer/class-astra-customizer.php
This fixes - Uncaught ReferenceError: wpColorPickerL10n is not defined JS error in customizer for wp-color-picker-alpha lib - https://github.com/kallookoo/wp-color-picker-alpha/issues/35
https://a.cl.ly/E0unPADp
Bug fix.
Tested with WP 5.5 to see if RGB starts working for colors or not.
> fix: WP 5.5 wpColorPickerL10n issue, RGB not working for wp-color-picker-alpha lib.

- inc/customizer/class-astra-customizer.php
Replacing newly introduced function `astra_wp_version_compare` to compare WP version.
Non-breaking changes.
Test if the existing fix for JS is still working or not. Working properly.
> improvement: Replace 'version_compare' with new 'astra_wp_version_compare' function.

- inc/core/class-gutenberg-editor-css.php
- data-align attr issues with GB blocks
- managed some CSS with new WP 5.5 version
- With 5.5 WP version
- With < 5.5 WP version
> fix: GB Editor fixes and align issues in wp5.5

- inc/customizer/custom-controls/background/class-astra-control-background.php
- inc/customizer/custom-controls/border/class-astra-control-border.php
- inc/customizer/custom-controls/color/class-astra-control-color.php
- inc/customizer/custom-controls/customizer-link/class-astra-control-customizer-link.php
- inc/customizer/custom-controls/description/class-astra-control-description.php
- inc/customizer/custom-controls/divider/class-astra-control-divider.php
- inc/customizer/custom-controls/heading/class-astra-control-heading.php
- inc/customizer/custom-controls/link/class-astra-control-link.php
- inc/customizer/custom-controls/radio-image/class-astra-control-radio-image.php
- inc/customizer/custom-controls/responsive-background/class-astra-control-responsive-background.php
- inc/customizer/custom-controls/responsive-color/class-astra-control-responsive-color.php
- inc/customizer/custom-controls/responsive-slider/class-astra-control-responsive-slider.php
- inc/customizer/custom-controls/responsive-spacing/class-astra-control-responsive-spacing.php
- inc/customizer/custom-controls/responsive/class-astra-control-responsive.php
- inc/customizer/custom-controls/select/class-astra-control-select.php
- inc/customizer/custom-controls/settings-group/class-astra-control-settings-group.php
- inc/customizer/custom-controls/slider/class-astra-control-slider.php
- inc/customizer/custom-controls/sortable/class-astra-control-sortable.php
- inc/customizer/custom-controls/typography/class-astra-control-typography.php
Fixes: PHP Notice:  Array to string conversion in C:\xampp\htdocs\hf-builder\wp-includes\formatting.php on line 1098
https://a.cl.ly/WnuJrq2Y
Bug fix.
Checked the debug log and now this error no longer exists.
> fix: Array to string conversion - PHP Notice issue fixed.

- inc/customizer/custom-controls/heading/class-astra-control-heading.php
The `ast-heading` control escaped the label HTML.
https://a.cl.ly/WnuJ5062
https://a.cl.ly/WnuJ5062
> fix: Astra Heading Control - Issue with & getting escaped.

- inc/customizer/class-astra-customizer.php
- inc/customizer/custom-controls/font-variant/class-astra-control-font-variant.php
- inc/customizer/custom-controls/typography/class-astra-control-typography.php
- inc/customizer/customizer-controls.php
- When we open the Settings Group popup containing Typography settings it does not open.
- Check Typography settings in Popup are working or not.
- Check Typography settings out of Popup are working or not.
- Check Font Variant control working or not.
> fix: Astra Typography not working in the Setting group.

- inc/builder/type/footer/social-icon/dynamic-css/dynamic.css.php
- inc/builder/type/footer/widget/dynamic-css/dynamic.css.php
- inc/core/builder/class-astra-builder-helper.php
- inc/customizer/configurations/builder/footer/class-astra-customizer-copyright-configs.php
- inc/customizer/configurations/builder/footer/class-astra-customizer-footer-social-icons-configs.php
- inc/customizer/configurations/builder/footer/class-astra-footer-widget-component-configs.php
- First, drag-dropped not shows preview correctly unless & until we Publish the customizer & reload it
- Corrected Builder type for Footer Social component
- Maintained Left | Center | Right alignment sequence as it should look like normally
- Example with Footer HTML - 2
- PS: When firstly it dragged & dropped alignment is Center but till customizer refresh (partial refresh) it does not reflect as expected
- https://a.cl.ly/mXuyezdk
- Adde a small `is_customize_preview` check in `is_component_loaded` function.
- With any Header / Footer component
- Verification in customizer preview
> fix: First drag-dropped component not previewing correctly

- inc/customizer/configurations/builder/header/class-astra-header-search-component-configs.php
Removed advanced search configs from theme & added in the addon.
- New feature (non-breaking change which adds functionality
- The Search style options appear only when the addon is active.
> refactor: Removed advanced search configs from theme & added in addon.

- inc/core/builder/class-astra-builder-options.php
This removes the default values set for Button.
Ideally, the button should inherit all the default styling from global options.
> fix: Inherit button styling from theme instead of defaults.

- inc/builder/type/header/search/dynamic-css/dynamic.css.php
- When we pass an empty value in Search Icon size then PHP warking shows in frontend.
- https://a.cl.ly/4guJ0z4R
Bugfix (non-breaking change which fixes an issue) 
- No warning when icon size passed empty.
> fix: Non - numeric variable php warning in Search dynamic CSS when passed empty.

- inc/assets/js/navigation.js
- inc/customizer/configurations/builder/header/class-astra-customizer-header-builder-configs.php
- Desktop to mobile layout change does not change the markup & partial refresh issue.
- https://a.cl.ly/YEuyNX0r
Bugfix (non-breaking change which fixes an issue) 
- Check Off-Canvas & Dropdown working or not.
- Check by changing devices in customizer if the proper markup loads or not.
- Check by triggering the partial refresh.
> fix: Desktop to mobile layout change does not change the markup & partial refresh issue.

- inc/builder/type/header/above-header/assets/js/customizer-preview.js
- inc/builder/type/header/above-header/dynamic-css/dynamic.css.php
- inc/builder/type/header/below-header/assets/js/customizer-preview.js
- inc/builder/type/header/below-header/dynamic-css/dynamic.css.php
- inc/builder/type/header/primary-header/assets/js/customizer-preview.js
- inc/builder/type/header/primary-header/dynamic-css/dynamic.css.php
Line height issue for Above/below/Primary header.
https://share.getcloudapp.com/L1uQ5B4j
> fix: Line height issue for Above/below/Primary header.

- inc/core/common-functions.php
fix: BG color not working after migration
Task - https://trello.com/c/sB8IdROf/213-bg-not-working-when-set-as-color-and-migrated-to-react-based-customizer
Before: https://d.pr/i/CbR2Gq
After: https://d.pr/i/CIhrtJ
Logic for BG color CSS generation improved.
> fix: BG color not working after migration

- inc/class-astra-dynamic-css.php
Global > Buttons > Hover color.
This property is not default inherited by the buttons in Header Footer builder.
This PR fixes the issue.
- Go to - Global > Buttons > Hover color
- See if the Hover Color is inherited by HFB buttons in frontend too.
> fix: Global button hover color inherit in HFB buttons

- inc/core/class-astra-enqueue-scripts.php
Changed the CSS animation loading logic in case of header builder and multiple menus, this also fixes a bug related to when users shift from old header builder to the new header builder.
Checked by taking different menus and their animation enabled then checking the page source to verify if the CSS loads.
> fix: Multiple menu animation CSS case.

- inc/core/builder/class-astra-builder-helper.php
Added Header and Footer Divider count restriction.
Add below code to your active themes Functions.php. The divider elements count in customizer should be less than 10 no matter what value is set from the below filter.
```
function astra_builder_elements_count( $elements ) {
$elements['header-button']       = 20;
$elements['footer-button']       = 20;
$elements['header-html']         = 20;
$elements['footer-html']         = 20;
$elements['header-widget']       = 20;
$elements['footer-widget']       = 20;
$elements['header-social-icons'] = 20;
$elements['footer-social-icons'] = 20;
$elements['header-divider'] = 20;
$elements['footer-divider'] = 20;
return $elements;
}
add_filter( 'astra_builder_elements_count', …
```
> fix:Added restriction for divider count

- inc/core/builder/class-astra-builder-helper.php
Handle the condition if a user does not pass any elements count to the filter. This will show a notice as an undefined variable.
https://a.cl.ly/ApuGrjOE
- Checkout to the main branch of Theme and Addon.
- Encountered this issue when putting the below code in your child themes Functions.php - 
```
function astra_builder_elements_count( $elements ) {
return array(
'header-button'       => 2,
'footer-button'       => 2,
'header-html'         => 2,
'footer-html'         => 2,
'header-menu'         => 2,
'header-widget'       => 2,
'footer-widget'       => 2,
'header-social-icons' => 2,
'footer-social-icons' => 2,
);
}
add_filter( 'astra_builder_elements_count', 'astra_builder_elements_count', 10 );
```
- In the above code, `header-divider` …
> fix: Handle the condition if any elements count missing in the filter

- inc/builder/type/header/menu/assets/js/customizer-preview.js
- Trello task - https://trello.com/c/zfw0vrsE/822-menu-stack-on-mobile-doesnt-work-in-the-customizer-preview
Bugfix (non-breaking change which fixes an issue) -->
- Check Stack on the mobile option in the customizer preview
> fix: Menu - Stack on mobile - Doesn't work in the customizer preview

- inc/core/builder/class-astra-builder-helper.php
- inc/customizer/configurations/builder/class-astra-builder-base-configuration.php
- inc/customizer/configurations/builder/header/class-astra-customizer-off-canvas-configs.php
- The Visibility settings are visible in both General & Design Tabs.
- No Duplicate settings.
> fix: Duplicate Visibility settings for all elements in both General & Design Tabs.

- inc/builder/type/header/menu/assets/js/customizer-preview.js
- Stack on the mobile option for Menu not working in the customizer preview.
- Stack on mobile works in the customizer preview.
> fix: Stack on mobile option for Menu not working in customizer preview.

- inc/addons/transparent-header/classes/sections/class-astra-customizer-colors-transparent-header-configs.php
- inc/customizer/configurations/builder/footer/class-astra-customizer-above-footer-configs.php
- inc/customizer/configurations/builder/footer/class-astra-customizer-below-footer-configs.php
- inc/customizer/configurations/builder/footer/class-astra-customizer-primary-footer-configs.php
- inc/customizer/configurations/builder/header/class-astra-customizer-above-header-configs.php
- inc/customizer/configurations/builder/header/class-astra-customizer-below-header-configs.php
- inc/customizer/configurations/builder/header/class-astra-customizer-primary-header-configs.php
- Added missed ASTRA_THEME_SETTINGS to customizer controls
- Ref PR - https://github.com/brainstormforce/astra/pull/2030
- This breaks controls which removed from setting group
- https://i.imgur.com/Xs6cI5n.png
- Added ASTRA_THEME_SETTINGS prefix to direct controls
- With Transparent Header > BG Overlay Color
- Above header - BG Color
- Primary header - BG Color
- Below header - BG Color
- Above footer - BG Color
- Primary footer - BG Color
- Below footer - BG Color
> fix: Added missed ASTRA_THEME_SETTINGS to customizer controls

- inc/core/builder/class-astra-builder-helper.php
- template-parts/header/builder/components.php
- Trello task - https://trello.com/c/fNSATv24/846-need-to-add-2-widgets-in-astra-theme-header
- New feature (non-breaking change which adds functionality)
- You can see 2 Widgets in the Header for Free Theme.
> fix: Added 2 Widgets in Astra Theme Header.

- inc/compatibility/edd/class-astra-edd.php
- inc/compatibility/woocommerce/class-astra-woocommerce.php
- inc/customizer/configurations/builder/header/class-astra-customizer-woo-cart-configs.php
- Theme check plugin gives an error if 2 Text domains are used in the Theme.
Bugfix (a non-breaking change that fixes an issue)
- Check with the Theme Check plugin.
> fix: Removed the astra-addon Text Domain used in the Theme.

- inc/customizer/class-astra-customizer.php
- Trello task - https://trello.com/c/zz7twLsK/876-padding-control-bug
- Bug fix (non-breaking change which fixes an issue)
1. Check the initial value it is storing as an empty string.
2. Edit it with any value and clear it. ( not 0 )
3. It stores an array with all values empty string (non-integer) it should be store as an empty string as initially stored to maintain consistency.
> fix: Inconsistency between the responsive spacing control empty values.

- inc/compatibility/woocommerce/class-astra-woocommerce.php
- PHP notice occurs in case of non-migrated users.
- Bugfix (a non-breaking change that fixes an issue)
- Import `Life Coach` Gutenberg Starter site in master Branch.
- Switch to `v3-milestones` & deactivate Astra Addon.
- Do not switch to `New Header Footer Builder`
- You will see PHP notice in the debug log.
> fix: PHP notice in the Woocomerce Cart element.

- inc/builder/type/header/edd-cart/dynamic-css/dynamic.css.php
- EDD cart hover icon color issue for none style
- https://d.pr/i/o3YBRA
- Dynamic CSS updated
- Test with EDD cart
> fix: EDD cart hover icon color issue for none style

- inc/builder/controllers/class-astra-builder-ui-controller.php
```
WARNING: Found ><?php echo esc_attr( in class-astra-builder-ui-controller.php. Only use esc_attr() inside HTML attributes. Use esc_html() between HTML tags. A manual review is needed.Line 350: <span class='ast-header-account-text'><?php echo esc_attr( $logged_in_text ); ?></span>Line 391: <span class='ast-header-account-text'><?php echo esc_attr( $logged_out_text ); ?></span>Line 423: <span class='ast-header-account-register'><?php echo esc_attr( __( 'Register', 'astra' ) ); ?></span>Line 431: <span class='ast-header-account-lostpass'><?php echo esc_attr( __( 'Lost your password?', 'astra' ) ); ?></span>
```
Theme check issue
> fix: Theme check esc_attr instead of esc_html fix.

- inc/assets/css/astra-admin-menu-settings.css
- inc/core/class-astra-admin-settings.php
- inc/core/class-astra-enqueue-scripts.php
- Removed NEW highlitening tag from Astra options for Header & Footer builder
- Non-breaking changes
- Astra Options page should be verified
> refactor: Removed NEW highlitening tag from Astra options for Header & Footer builder

- inc/builder/type/base/dynamic-css/button/class-astra-button-component-dynamic-css.php
- inc/builder/type/header/mobile-menu/dynamic-css/dynamic.css.php
- inc/builder/type/header/mobile-trigger/dynamic-css/dynamic.css.php
- inc/core/builder/class-astra-builder-helper.php
- https://trello.com/c/SmhTYqTW/927-iscomponentloaded-params-function-improvement
- Added builder type and device type checks in `is_component_loaded ` function.
-  Added header-desktop, header-mobile, header-both, footer and all devices array to check device and builder wise components.
- For other function call their is no need to change parameters as it has already handled in both device Cases.
- Improvements
- Add component to specific header/footer and specific device and check if dynamic respective CSS is loaded or not.
- Load only that components dynamic CSS in which component is being loaded.
> imprv: Revamp is_component_loaded function

- inc/theme-update/astra-update-functions.php
[Task](https://trello.com/c/CJWxzky1/947-empty-customizer-migration-issue-in-v300)
- Go to stable version of Astra theme (2.6.2).
- Now reset the site it means you have a fresh new setup on this stable version.
- Then switch to next-release branch of theme.
- Enable the new header footer builder from the Astra options page and reload the page on the front end.
You will see that the header is missing from the front end like [this](https://share.getcloudapp.com/v1u4GPKj)
The header builder is missing from customizer as well : [Screenshot](https://share.getcloudapp.com/p9ur4ep5)
> fix: Fix when there is blank data to migrate.

- changelog.txt
- inc/theme-update/astra-update-functions.php
- inc/theme-update/class-astra-theme-background-updater.php
This issue occurs when the user updates Astra Pro first & then the theme.
https://a.cl.ly/qGuleOdq
Caching issue.
https://a.cl.ly/qGuleOdq
> fix: This fix clears assets cache and regenerates new assets files.

- inc/class-astra-dynamic-css.php
- Corrected alignful selector to alignfull selector
- No need to mention this in changelog
- Non-breaking changes
- With GB designed page having cover block
- Firstly set " Full Width / Stretched" layout for page
- Assign "Right Sidebar"
- Take cover block with alignfull content
- Check on frontend from previous version & after switching to this branch
> refactor: Selector spell corrected for alignfull class

- inc/customizer/configurations/builder/class-astra-builder-base-configuration.php
- Trello task - https://trello.com/c/RNMIxbwO/1103-font-size-isnt-applying-in-the-copyright-widget
- Check Font Size working for above mentioned elements  or not when the addon is deactive.
> fix: Font Size not working for HTML, Social, Copyright, Account for addon deactive or Typography options deactive  case.

- inc/builder/controllers/class-astra-builder-ui-controller.php
- Trello task - https://trello.com/c/toveEmYA/1150-mobile-header-not-visible
- Check by Switching devices the Desktop & Mobile headers should be visible.
> fix: Mobile/Desktop Header not visible if we switch contexts.

- inc/customizer/configurations/builder/base/class-astra-button-component-configs.php
- Fixed error due to Addon's builder instance used in theme
- https://share.getcloudapp.com/04uJ2WDw
- https://share.getcloudapp.com/4gu1n4AD
- Fixing error
- Check theme customizer when addon is deactiavted
> fix: Fatal error due to addon builder instance used in theme context

- inc/customizer/configurations/builder/header/class-astra-customizer-site-identity-configs.php
- inc/customizer/configurations/builder/header/class-astra-header-menu-component-configs.php
- inc/customizer/configurations/typography/class-astra-header-typo-configs.php
- Double divider appearing in site identity section
- https://a.cl.ly/yAu6rAwX
- Non breaking change
- Check with addon deactivate
> fix: Double divider case resolved in Site Identity section

- inc/compatibility/woocommerce/customizer/sections/layout/class-astra-woo-shop-single-layout-configs.php
The divider is missing in the transparent header setting
https://a.cl.ly/P8ukGDDA
Bug fix
> fix: Added missing divider for Woo Pages toggle for Transparent header.

- .github/workflows/stale.yml
I believe 120 days is too large, If there is no activity after 5 days after the notification is sent, We can close the PR.
Do let me know what you guys think.
> Reduce the stale PR close delay to 5 days

- inc/core/class-astra-admin-settings.php
- template-parts/footer/builder/components.php
- template-parts/header/builder/components.php
Fixed SonarLint issues related to missing attribute in HTML elements
> fix: Sonarlint attribute missing in element issue

- inc/core/class-gutenberg-editor-css.php
- inc/core/common-functions.php
- inc/theme-update/astra-update-functions.php
- inc/theme-update/class-astra-theme-update.php
- template-parts/header/builder/header-row.php
- template-parts/header/builder/mobile-header-row.php
Fixed SonarLint issues related to useless parentheses added in code
> fix: Sonarlint remove useless parentheses issue

- inc/class-astra-dynamic-css.php
- inc/class-astra-loop.php
- inc/compatibility/class-astra-beaver-builder.php
- inc/compatibility/class-astra-elementor.php
- inc/compatibility/class-astra-ubermeu.php
- inc/compatibility/class-astra-visual-composer.php
- inc/compatibility/woocommerce/class-astra-woocommerce.php
- inc/core/common-functions.php
- inc/customizer/class-astra-customizer-callback.php
- inc/customizer/class-astra-customizer-partials.php
Fixed SonarLint issues related to strict operator checking in conditional statements
> fix: SonarLint strict operator condition check fix

- inc/core/markup/class-astra-markup.php
Email and website field not align for single post comment form.
Please go to single post comment form without login and check Email, Website and Name field you will see  the Issue.
Issue - https://share.getcloudapp.com/YEuX5lqd
Fix- https://share.getcloudapp.com/OAugpE0y
Issue.
> fix: email and website field not align for single post comment form

- inc/extras.php
Menu clone - SVG Icons missing when menu is changed from cloned menu to some other menu.
Bug fix
> AST-266 - fix: Menu clone - SVG Icons missing when menu is changed from cloned menu to some other menu.

- inc/customizer/configurations/layout/class-astra-related-posts-configs.php
- Added context dependency for typography & color settings options which are based on title-meta in Related Posts structure
- https://share.bsf.io/YEuRO8GO
- https://share.getcloudapp.com/E0uYj6Dw
- Non breaking change
- With Related Posts structure
> AST-375 - refactor: Added context dependency for Title-meta & color settings based on post structure

- inc/class-astra-dynamic-css.php
- Made equal spacings of 1em in all possible cases of Related Posts structure
- https://share.getcloudapp.com/DOuDBWbW
- https://share.getcloudapp.com/RBuYLN84
- https://share.getcloudapp.com/WnuY01jY
- In some cases already 1em spacing is there but after image section any section don't have much spacing
- So made this equal to 1em
- With Related Posts
> AST-377 - fix: Spacing make equal to 1em in between all possible combinations in Related Posts

- inc/class-astra-dynamic-css.php
- inc/core/class-astra-theme-options.php
- inc/customizer/configurations/layout/class-astra-related-posts-configs.php
- Added default line-height to 1 & top-bottom margin space for individual post title & Related Posts 
- https://share.getcloudapp.com/Blu4xgGB
- Default updated
- Corrected priority of Enable Related Posts toggle control as one of addon's control overriding that
- Updated static CSS for top-bottom margin space
- With Related Posts section
> AST-376 - improvement: Added default line-height & margin space for post title in Related Posts

- inc/class-astra-dynamic-css.php
- Section should be strict in container width when it is FullWidth Stretched
- Issue - https://share.getcloudapp.com/wbuwbAvz
- CSS updated
- Optimized static CSS with duplicate ones and make it common CSS with merging selectors
- With Related Posts section
> AST-372 - fix: Full width Stretched layout width compatibility with Related Posts section

- changelog.txt
- inc/compatibility/class-astra-elementor.php
- Layout issue on an Archive page created using Elementor.
- https://wp-astra.atlassian.net/browse/AST-383
-  Due to flex property for primary and secondary content the elementor archive page without sidebar causing the layouts issue.
- I have also very with other theme like GP with same flex property for primary and secondary and they have managed by adding compatibility CSS.
> AST-383 - fix: Elementor archive page layout issue

- inc/compatibility/lifterlms/class-astra-lifterlms.php
- inc/compatibility/lifterlms/customizer/class-astra-liferlms-section-configs.php
- inc/compatibility/lifterlms/customizer/sections/layout/class-astra-lifter-general-configs.php
- LifterLMS section missing in customizer because their controls file did not loaded
- Doc Link - https://wpastra.com/docs/lifterlms-free/ 
- https://share.bsf.io/Blu4RJdg
- With Lifter plugin
- With free Astra theme
> AST-399 - fix: Lifter LMS section missing in customizer because file require code was missing from v3.0.0

- changelog.txt
- inc/core/class-gutenberg-editor-css.php
- Grey BG color creates overlay in editor when layout is full-width contained & stretched
- v3.4.0 - https://d.pr/i/8grmtw
- v3.1.0 - https://share.bsf.io/2Nuw8YYp
- With fix - https://share.bsf.io/geub7vxj
- Bug fix
- With GB editor
- With Full-Width Co0nteined + Stretrched layout
> AST-430 - fix: GB editor facing grey overlay in editor when layout is full-width

- changelog.txt
- inc/extras.php
https://github.com/brainstormforce/astra/pull/2664 - cherry pick
> fix: Cherry-pick Page Builder's menu elements shows double arrow icons when Astra's SVG icons are enabled.

- changelog.txt
- inc/core/class-gutenberg-editor-css.php
- inc/core/common-functions.php
- #2718
- This PR fixed the following Issues:
- Block selection color not working
- Place holders not visible when the default(white) background is set for the content.
- Image caption not visible in the editor view.
https://share.getcloudapp.com/Jru4Q0B0
Cases mentioned in task - https://wp-astra.atlassian.net/browse/AST-464
> chore: Cherry-pick editor selection color not working in after wp-5.7 versions.

- inc/compatibility/class-astra-web-stories.php
In the web stories plugin version 1.7.1, the code was refactored and plugin structure got changed. 
Updated web stories code as per the refactoring of web stories. See https://github.com/google/web-stories-wp/pull/7266/files
Bug fix - web stories customizer disappeared due to recent web stories refactor changes.
> Update customizer call as per web stories refactored code

- inc/class-astra-dynamic-css.php
- Spacing css missing when inline logo and title option is enabled.
- https://wp-astra.atlassian.net/browse/AST-511
fix - https://share.bsf.io/Wnux1p5q
> AST-511 - fix: spacing CSS missing when inline logo and title option is enabled

- changelog.txt
- inc/customizer/class-astra-customizer.php
There is a console error in the customizer view when the plugin is active. This error is from the JS which is added for the block editor support for widgets from the Gutenberg plugin. As of now I have added a filter to disable block editor support.
https://share.getcloudapp.com/xQu7ZlE8
Checked the working of customizer with and without the Gutenberg plugin.
> AST-554 Fix: Customizer not working when Gutenberg plugin v10.7.0 and above is active.

- README.md
- changelog.txt
- functions.php
- inc/customizer/class-astra-customizer.php
- languages/astra.pot
- package-lock.json
- package.json
- readme.txt
- style.css
---
---
v3.4.8
- Fix: Customizer not working when Gutenberg plugin v10.7.0 and above is active.
> Build: Release PR Cherry picked fix of Customizer not working when Gutenberg plugin is active.

- changelog.txt
- functions.php
- inc/theme-update/astra-update-functions.php
- inc/theme-update/class-astra-theme-background-updater.php
- Added cache clearing batch trigger with version 3.6.1
- Bug fix + Non-breaking change
- Builder desktop + mobile header in past older version of Astra + Astra Addon
- Make sure Enabled File Generation there.
- After updating to the master of Astra will get this issue on frontend - https://share.bsf.io/OAuQP4Ae
- Now test in this branch - as soon as updates to this version v3.6.1 issue must be fixed
> AST-585 - Added cache clearing batch function for v3.6.1 in Astra

- changelog.txt
- inc/modules/related-posts/class-astra-related-posts-markup.php
- Meta markup structure for Related Posts showing structure based on active post
- Issue - https://drive.google.com/file/d/1hhdVBekMi1SdRPrHw4tg4PwUZGh9aGM7/view
- Issue with master - https://share.bsf.io/xQu7jLgr
- With this PR - https://share.bsf.io/4gunP9yD
- Bug fix
- Moved meta query structure from before loop to inside loop
- With above explanatory video
> AST-596 - Individual related post article showing meta markup based on current post filters

- changelog.txt
- inc/customizer/class-astra-fonts.php
- Preloading option affects height 100% for cover edit block
- https://drive.google.com/file/d/1DoaLJf_oaRAujnJYDDogosqxP4XwvS0R/view
- Bug fix 
- As steps mentioned here - https://wp-astra.atlassian.net/browse/AST-604
> AST-604 - 'Preload Local Fonts' option affects on height of Gutenberg Cover edit block

- inc/class-astra-dynamic-css.php
- Due to CSS priority Header and Menu are not aligned after dynamic breakpoint changes.
- https://wp-astra.atlassian.net/browse/AST-529
- Link PR- https://github.com/brainstormforce/astra/pull/2845
Issue - https://share.getcloudapp.com/yAurkl0o
Fix - https://share.getcloudapp.com/4gunZJZy
> AST-529 - fix: Due to CSS priority Header and Menu are not aligned after dynamic break point changes.

- composer.json
- composer.lock
- psalm.xml
- tests/php/static-analysis-stubs/astra-stubs.php
Psalm is requiring us to maintain stub file for it to understand the codebase of Astra.
This PR adds a command `composer run update-stubs` which will update the stubs file.
This command basically runs `grunt release-no-clean` command and passes the release directory to [stubs-generator](https://github.com/php-stubs/generator)
> Include a update-stubs command to update Astra stubs

- changelog.txt
- inc/builder/type/footer/widget/dynamic-css/dynamic.css.php
- inc/class-astra-dynamic-css.php
- The Cart, on responsive devices such as Mobile, when adding too many Products, It can’t scroll to get Cart & Checkout buttons
- Dev site - http://ast-dev.xka9ibwowp-jqp3vd915350.p.runcloud.link/local-google-fonts/testing-fonts/
- https://share.bsf.io/z8uOrP6e
- Bug fix
- Add multiple products to the cart 
- Check on responsive devices inside the flyout
> AST-622 - Builder - WooCommerce & EDD cart - Cart and Checkout buttons not visible when multiple products added to cart flyout

- bin/scripts/dynamic-css-to-file.js
- package-lock.json
- package.json
Pupeeteer is already included through @wordpress npm dependencies. This change will reduce some time required for `npm install` and hence the build time in CI.
> Remove puppeteer dependency

- package-lock.json
- package.json
Reverts brainstormforce/astra#2987
Fix: Grunt minify not working due to incompatibility with autoprefixer latest version and post-css current version.
> Revert "build(deps-dev): bump autoprefixer from 9.8.6 to 10.3.1"

- changelog.txt
- inc/core/class-astra-admin-settings.php
- psalm.xml
- tests/php/psalm-baseline.xml
- v3.6.6 release PR - https://github.com/brainstormforce/astra/pull/3048/
- https://wp-astra.atlassian.net/browse/AST-738
- As astra-admin-settings-js script loading on admin end, this has 'updates' script dependency which stopped bulk selection on setup. This leads to an issue of failing our Github test cases.
- https://share.bsf.io/rRubyJkv
- Bug fix 
- Cases has been  added in card
> AST-738 - Bulk action selection not working when Astra Get Started notice is active

- changelog.txt
- inc/builder/markup/class-astra-builder-header.php
- Offcanvas header & cart flyout menu's content displaying over preview of Legacy widgets in customizer WP5.8
- https://share.bsf.io/wbubA5wL
- Bug fix 
- Test cases as follows -
- 1. Use Legacy widget (of any Menu/Archive widget)
- 2. Then set header Offcanvas style as Flyout or Fullscreen
- 3. Reload the customizer page
- 4. You will see the content from offcanvas & from flyout cart on widget preview screens
- Other test cases to test
- As we are changing wp_footer action here which loaded flyouts markup for header offcanvas & for Woo/Edd cart
- Make sure to test those functionalities as well
- Header flyout/full-screen
- Cart flyout
> AST-739 - Offcanvas header's preview is displaying on Legacy widget's preview in customizer of WordPress 5.8.

- changelog.txt
- inc/compatibility/class-astra-elementor-pro.php
- inc/core/builder/class-astra-builder-helper.php
- Elementor Pro's built header/footer layouts not override Astra's new Header-Footer builder layouts where as it works with oild header-footer layout
- Issue- - https://share.bsf.io/E0uAZ5YQ
- Working with old header-footer layout - https://share.bsf.io/qGu5xj8z
- Bug fix 
- Design header-footer layouts from Elementor+Elementor pro
- Check if its override Astra's header-footer in both old & new HFB cases
> AST-634 - Elementor Pro's Header-Footer theme builder layouts does not override theme's Header-Footer builder layouts

- changelog.txt
- inc/compatibility/class-astra-elementor-pro.php
- Cherry-picked PR - https://github.com/brainstormforce/astra/pull/3073
- Elementor Pro's Header-Footer theme builder layouts does not override theme's Header-Footer builder layouts
- Task- https://wp-astra.atlassian.net/browse/AST-634
- non-breaking change 
- Design header-footer layouts from Elementor+Elementor pro
- Check if its override Astra's header-footer in both old & new HFB cases
> chore: Cherry picked 3073 PR

- .wp-env.json
- bin/scripts/pre-e2e-tests.sh
- tests/e2e/config/bootstrap.js
Currently, Gutenberg nightly gets auto-installed each time you run the tests locally, After several runs you get too many copies installed.
This PR installs this plugin from wp-env. wp-env auto-activates any plugins/themes that are installed, so this is deactivated as before ll tests. This can be activated in each test with Gutenberg editor.
Passing e2e tests
> Gutenberg nightly auto installed from wp-env

- .github/.wp-env-themecheck.json
- .github/workflows/theme-check.yml
- .wp-env.json
- package.json
We run theme-check in GitHub actions and theme-check cannot have all extra build/development files in the theme for eg `.git`, `phpcs.xml.dist` etc.
To fix this we have been building the Astra theme and including the built directory in the wp-env. but this causes limitations when writing e2e tests as now your working directory in the local environment is not mounted in the docker but the "built" directory is.
To fix this, this PR creates separate wp-env environments for all other cases and theme checks, for theme check we still keep the existing approach to build the theme and mount the built directory but for e2e test we are mounting the current working directory of the theme.
Passing e2e tests
> use separate wp-env for theme-check and e2e tests

- changelog.txt
- inc/class-astra-dynamic-css.php
- https://wp-astra.atlassian.net/browse/AST-583
-  Woo cart products count is overlapping on the submenu section.
- https://share.bsf.io/v1uYYl4o
> AST-583 - fix: Woo cart products count is overlapping on the submenu section

- changelog.txt
- inc/class-astra-dynamic-css.php
- https://wp-astra.atlassian.net/browse/AST-794
- Logo is flickering on mobile device due to mobile logo width is getting appllied late.
- REf- https://websitedemos.net/online-health-coach-02/
> AST-794 - fix: desktop logo width is applying for a moment on mobile device

- inc/customizer/class-astra-customizer.php
- inc/customizer/configurations/typography/class-astra-body-typo-configs.php
- inc/customizer/configurations/typography/class-astra-content-typo-configs.php
- inc/customizer/configurations/typography/class-astra-global-typo-configs.php
- inc/customizer/configurations/typography/class-astra-headings-typo-configs.php
> Loading typography section for H3-H6 conditionally

- inc/class-astra-global-palette.php
- inc/compatibility/class-astra-elementor.php
- inc/core/builder/class-astra-builder-options.php
Modified Palette color labels to Color 1, color 2 ... Also displaying labels as Theme color 1, Theme color 2 .. in Gutenberg and Elementor Color editor.
> GCP-150 Modified labels for Palette colors

- inc/builder/type/footer/copyright/dynamic-css/dynamic.css.php
- inc/core/builder/class-astra-builder-options.php
- inc/theme-update/astra-update-functions.php
Copyright text color is linked with text color option. Added backward compatibility for the same.
> GCP-151 Added backward compatibility for copyright text color

- inc/addons/breadcrumbs/dynamic-css/dynamic.css.php
- inc/compatibility/learndash/customizer/sections/class-astra-learndash-container-configs.php
- inc/compatibility/lifterlms/customizer/sections/class-astra-lifter-container-configs.php
Need divider in the customizer setting for third-party plugin settings as shown in the screenshot below.
https://share.getcloudapp.com/rRubpn0v
Checked the layout options for the learn dash and lifterLMS plugins.
> AST-733 chore: added divider for third party plugin compatibility options in customizer.

- inc/class-astra-global-palette.php
- inc/compatibility/class-astra-elementor.php
- inc/theme-update/class-astra-theme-background-updater.php
Modified color palette slugs according to color 1, color 2 .. format to be used in Elementor global color slugs.
> Modified color palette slugs used in Elementor compatibility for palette

- .github/workflows/pull-request-title.yml
PR title requirement does not need to be executed on intermediate branches.
Fixes PRs against development branches being marked as failed.
https://github.com/brainstormforce/astra-addon/pull/315
> AST-927 - Require PR title requirement only on the main branches

- changelog.txt
- inc/metabox/class-astra-meta-boxes.php
- Disable above header option is not visible in the meta settings.
- Alos Astra meta settings are visible in Custom Layouts
- https://wp-astra.atlassian.net/browse/AST-1284
https://share.getcloudapp.com/X6ub9dRv
> AST-1284 - fix: disable above header option is not visible in the meta settings

- functions.php
- inc/core/builder/class-astra-builder-options.php
- inc/core/class-astra-theme-options.php
- inc/extras.php
- inc/theme-update/astra-update-functions.php
- inc/theme-update/class-astra-theme-background-updater.php
- tests/php/static-analysis-stubs/astra-stubs.php
- Currently some elements or areas have colors assigned hard-coded in defaults or come from static CSS
- So updating those colors by linking them to color palette
- Example - https://share.bsf.io/v1ujq6kO
- Improvement
- Check builder areas elements -
- 1. Above header - Border bottom, Background color
- 2. Primary header - Border bottom, Background color
- 3. Below header - Border bottom, Background color
- 4. Site Indetity - Title, Tagline colors
- 5. Social element - Header + Footer - Icon, Label color
- 6. Account element - Icon color
- 7. HTML element - Text, Link color
> AST-1424 - Linked default builder element's colors to color palette colors to make them sync with switcher mode

- inc/class-astra-dynamic-css.php
If we add more than 5 digits to the default icon, it will break the icon layout to vertical on responsive devices.
- https://share.bsf.io/nOu5jmrN   
- https://share.bsf.io/Jrun2WvO
- Add 5 digits in the cart using inspect and check on mobile and tab device.
> AST-1025 - Cart Icon CSS issue

- tests/e2e/specs/block-editor/list-block/list-block-width.test.js
- Create a new post
- Insert gutenberg List block and add some content
- Check width
https://share.getcloudapp.com/Qwu4YNRe
Run single test: npm run test:e2e:interactive tests/e2e/specs/block-editor/list-block/list-block-width.test.js
> QAE-309 - E2E test case for gutenberg list block

- changelog.txt
- inc/assets/css/block-editor-styles-rtl.css
- inc/assets/css/block-editor-styles.css
- sass/admin/block-editor-styles.scss
Removing unwanted Gutenberg block padding which causes Gutenberg blocks to jerk when clicked.
CSS which adds padding to blocks is not needed.
Even in 5.8, this CSS was causing the same issue.
There is no need to handle backward capability.
As padding should not be added to block on select, so we have eliminated it.
Before Fix - https://share.getcloudapp.com/P8u6YpYD
After Fix - https://share.getcloudapp.com/6quELWPq
1. Add Some text or any other Gutenberg blocks in the editor.
2. Now Click on any block to edit the content.
3. You will find, when clicked it's jerking.
> AST-1516 - Removing unwanted padding which causes Gutenberg blocks jerks when clicked.

- changelog.txt
- inc/core/class-gutenberg-editor-css.php
The blocks editor displays the headings and paragraphs differently than the front end when the Astra Parent theme is activated.
Switching to the child theme reduces the padding but there is still some padding left as compared to other themes.
Refer to the screencast for a detailed view:
Video:- https://d.pr/v/qzjIV6
Breaking editor layout change 
Added in the card.
> AST-1528 - Block Editor Layout Issue with Astra Parent Theme Editor layout issue

- tests/e2e/specs/customizer/header-builder/overall-header-settings/width.test.js
Run test: npm run test:e2e:interactive tests/e2e/specs/customizer/header-builder/overall-header-settings/width.test.js
> QAE-220 - E2E test case for header builder width option

- inc/class-astra-dynamic-css.php
- inc/compatibility/woocommerce/class-astra-woocommerce.php
- inc/core/class-astra-theme-options.php
- WooCommerce container 3em padding updated as like other in boxed layout
- Reverted 60px from customizer option as managed by static CSS
- non-breaking change 
- Check with transparent header
- Check full-width contained layout cases as discussed
- Check WooCOmmerce boxed layout
> AST-1926 - Reverted default updation for single container as this managed by basic CSS

- inc/compatibility/woocommerce/class-astra-woocommerce.php
- inc/theme-update/astra-update-functions.php
- inc/theme-update/class-astra-theme-background-updater.php
- Content Layout & Sidebar Layout priorities will be -
- 1. Individual setting
- 2. WooCommerce General settings
- 3. Global default
- 1. Check backward for old users - filter dependent
```
add_filter( 'astra_get_option_astra-ecommerce-modern-setup', '__return_true' );
```
- 2. Check as fresh user
- 3. Check dependencies
> AST-1956 - Added dependency for woocommerce general layouts to its archive and single product

- inc/builder/type/header/woo-cart/dynamic-css/dynamic.css.php
- inc/class-astra-global-palette.php
- inc/theme-update/astra-update-functions.php
Cart icon color fix when transparent header is enabled 
Checked when transparent header is enabled 
Checked when transparent header is disabled 
Checked when transparent color is not set
Checked icon with outline and fill properties 
Checked custom with color and hover
> AST-1973 - Fix Cart icon color when transparent header is enabled

- changelog.txt
- inc/compatibility/woocommerce/class-astra-woocommerce.php
If we click on the cart icon without hovering, previously, it will redirect to the cart page but after the latest update, there is no link to redirect to the dropdown cart.
ticket:- https://secure.helpscout.net/conversation/1956676466/210078/
> AST-2030 - WooCommerce cart Icon link is not working with the Dropdown cart

- changelog.txt
- inc/addons/breadcrumbs/customizer/class-astra-breadcrumbs-typo-configs.php
- inc/customizer/configurations/builder/base/class-astra-button-component-configs.php
- inc/customizer/configurations/builder/class-astra-builder-base-configuration.php
- inc/customizer/configurations/builder/footer/class-astra-customizer-footer-menu-configs.php
- inc/customizer/configurations/builder/header/class-astra-header-menu-component-configs.php
- inc/customizer/configurations/builder/header/class-astra-mobile-menu-component-configs.php
- inc/customizer/configurations/typography/class-astra-archive-typo-configs.php
- inc/customizer/configurations/typography/class-astra-header-typo-configs.php
- inc/customizer/configurations/typography/class-astra-headings-typo-configs.php
- inc/customizer/configurations/typography/class-astra-single-typo-configs.php
- inc/modules/related-posts/customizer/class-astra-related-posts-configs.php
Fixed step count for range slider when em is selected
https://d.pr/i/w6ZG1R
- Checked if the change is effected in customizer on various range sliders
> AST-2042 -  Fix step count for range slider when em is selected

- changelog.txt
- inc/assets/css/astra-admin-menu-settings-rtl.css
- inc/assets/css/astra-admin-menu-settings.css
- inc/core/class-astra-admin-settings.php
- tests/php/static-analysis-stubs/astra-stubs.php
- Spectra plugin admin redirection url corrected & added highlight label
- Highlight label - https://share.bsf.io/z8uQAwed
- Redirect url - https://share.bsf.io/DOurnGOY
- Bug fix (redirect url) 
- non-breaking change 
- 1. Redirect url
- - Check by activating plugin from Astra options page
- - The link should redirect to proper spectra page
- - Check with installed plugin activation
- - Check with install then activate plugin case
- 2. Highlight label
- Check UI
> AST-2134 - Spectra plugin admin redirection url corrected & added highlight label for plugin

- inc/compatibility/woocommerce/class-astra-woocommerce.php
Free shipping position issue when astra addon is disabled
Jira : https://brainstormforce.atlassian.net/browse/AST-2145
https://d.pr/i/H6GhLw
Checked if free shipping text comes properly when astra addon is disabled
> AST-2145 - Free shipping position issue when astra addon is disabled

- inc/core/class-astra-admin-settings.php
We need to [update this text](https://d.pr/i/OzfigH) on the Astra Options sidebar, as we have [230+ templates](https://wpastra.com/starter-templates/?page-builder=elementor) now. Reference: https://d.pr/i/OzfigH
https://d.pr/i/OzfigH
> AST-2185 - Update: Astra Options sidebar Template widget count

- inc/compatibility/woocommerce/customizer/sections/layout/class-astra-woo-shop-misc-layout-configs.php
Jira : https://brainstormforce.atlassian.net/browse/AST-2190
https://d.pr/i/VF89zn
- Checked when astra addons is enabled and disabled
> AST-2190 - Remove tabs in woocommerce misc section when addons is disabled

- inc/builder/type/header/woo-cart/dynamic-css/dynamic.css.php
- inc/compatibility/woocommerce/class-astra-woocommerce.php
Jira : https://brainstormforce.atlassian.net/browse/AST-2191
https://user-images.githubusercontent.com/28552974/188547654-87cba7a3-fb10-4724-bc9b-dd1cb2640723.png
- Checked with transparent mode 
- Checked with svg and css mode 
- Checked responsive
> AST-2191 - Border not showing up when astra addon is disabled

- inc/customizer/extend-custom-controls/build/index.asset.php
- inc/customizer/extend-custom-controls/package-lock.json
- inc/customizer/extend-custom-controls/src/ast-toggle/form-toggle.js
- inc/customizer/extend-custom-controls/src/ast-toggle/toggle-control.js
- Removed direct deps of lodash from customizer build
- non-breaking change
- verify customizer's ast-toggle control
> AST-2276 - removed direct dependency of lodash in customizer build

- changelog.txt
- inc/core/builder/class-astra-builder-admin.php
- inc/core/common-functions.php
currently, users need to understand, new features and options are no longer supported by the old header footer, They need to move on to new HF to use those option compatibility. so need to update the string on Astra setting page.
> AST-2279 - Old HF string changes on the Astra setting page improve.

- inc/core/class-astra-wp-editor-css.php
- For buttons need to remove WordPress CSS viz added in 6.1 because it’s overriding with our CSS
- https://d.pr/i/LCkRf1
- Bug fix
- Check the editor of WordPress 6.1
- Drag-drop buttons in editor to get the issue
> AST-2364 - Button editor styles gets overridden by WP-6.1

- inc/customizer/configurations/layout/class-astra-site-layout-configs.php
- Need to show both the sliders "Container Width" & "Narrow Width" Sliders when "Site Layout" is set to "Full Width"
- Updated name of the "Narrow Container Max Width"
https://d.pr/i/86PMu8
- Updated configs for site layout global container settings
- Check the Global > Container settings
> Fix: Updated site layout config & changed name of the NWL width slider

- changelog.txt
- inc/core/class-gutenberg-editor-css.php
**Test Data: (If any)**  
The button background colour is not applied in the editor for specific templates. 
1. Install any e-commerce starter template.
2. Go to the editor, and add the normal button.
3. Check the button normal and hover the colour on frontend and backend.
4. In the frontend, it looks fine, but in the editor, its normal colour is not added to the button.
**Actual Result:**
The button background colour is not applying properly. 
**Expected Result:** 
The button background colour must be applied properly. .
> AST-2569 - Cherry Pick fix: Button background colour must be selected issue in the editor for specific templates - Cherry Pick

- inc/modules/posts-structures/css/single-dynamic.css.php
AST-2738 - Fixed the text decoration issue for single post page
Minor class selector changed
> AST-2738 - Fixed the text decoration issue for single post page

- inc/customizer/configurations/layout/class-astra-site-layout-configs.php
- inc/dynamic-css/block-editor-compatibility.php
- inc/dynamic-css/content-background.php
- Content bg color should apply when narrow width container layout is selected.
- Removed context from Container Width slider. Now it will be visible for all cases.
JIRA - https://brainstormforce.atlassian.net/browse/AST-2764
https://d.pr/v/nLDFtS
bugfix: Content bg color should apply when narrow width container layout is selected.
bugfix: Container Width slider should show in all cases no matter which layout is selected.
- Select Narrow Width Container.
- Select "Content Background" set to any color.
- View in frontend, the Content Background color should be applied.
- Check if Content Background color is applied for responsive devices.
- Check if Content Background color is applied for editor.
> AST-2764 - Narrow width bugfixes

- .github/workflows/theme-check.yml
- inc/builder/type/header/woo-cart/dynamic-css/dynamic.css.php
- inc/dynamic-css/block-editor-compatibility.php
Margin top for entry header breaks preview design on responsive screens. It was earlier introduced during block editor improvements fix to match tablet view header in editor. But due to the top spacing breaking design, we need to revert the fix.
JIRA - https://brainstormforce.atlassian.net/browse/AST-2774
https://share.bsf.io/llugNy8y
- bugfix: remove CSS breaking UI
Steps to replicate:
- Get site reset / fresh setup
- Will get wp-preview templates in customizer
- Make it active-n-publish
- Check on frontend with responsive view.
> AST-2774 - fix: top spacing breaks UI, therefore needs to be removed.

- changelog.txt
- inc/core/common-functions.php
- Category/Tag like archive titles gets added as prefix on archive page titles as used core function `the_archive_title` for that.
- https://d.pr/i/RjFLPe
- Bug fix (non-breaking change)
- Switch to 3.9.4 version you will get only title of your taxonomy like this - https://share.getcloudapp.com/OAu22Egx
- Once switch to master (released version) will get this - https://share.getcloudapp.com/d5uyyxwE
- With this branch this should be resolve, there should not be any prefix.
> AST-2856 - Archive type title gets added as prefix on archive pages

- changelog.txt
- inc/blog/blog.php
- inc/modules/posts-structures/class-astra-posts-structure-loader.php
- Case: cartflows_step CPT is not getting listed under custom post types in customizer
- Which leads in unable to handle title frontend for it
- https://share.getcloudapp.com/lluggrbQ
- Bug fix (non-breaking change)
- As per listed data on card
> AST-2861 - exclude_from_search query param removed for getting post types

- changelog.txt
- inc/theme-update/astra-update-functions.php
- Text gets transforms after 4.0 for single title & archive title
- Bug fix (non-breaking change)
- v3.9.4 version https://share.getcloudapp.com/lluggqAz
- Reset the customizer, you will get above layout by default
- Now switched to master while processing batch the update it gets transformed to 'capitalize' - https://share.getcloudapp.com/yAuAAOep
- For already updated user they have option to make it disable from Title area as I suggested here - https://brainstormforce.slack.com/archives/CDS7TQ75Z/p1673844330438709?thread_ts=1673740912.844489&cid=CDS7TQ75Z
- But those who will update from v3.9.4 will not get this issue in this branch
> AST-2864 - Text transformed to 'capitalize' for single post titles & archive titles after 4.0.0

- changelog.txt
- inc/blog/single-blog.php
- inc/builder/type/footer/menu/dynamic-css/dynamic.css.php
- inc/builder/type/footer/widget/dynamic-css/dynamic.css.php
- inc/compatibility/woocommerce/class-astra-woocommerce.php
- inc/core/class-astra-wp-editor-css.php
- inc/dynamic-css/block-editor-compatibility.php
- inc/theme-update/astra-update-functions.php
- When we released 4.0 at that time users were faced this issue where post title case was switched to capitalize. 
- In 4.0.2 we fixed this issue but for users who will jump from 3.9.4 directly (by considering we are not getting much ticket, and users have option so they can adjust it)
- But as we are still getting those tickets planning to release patch for this.
- https://share.getcloudapp.com/wbuvlXZ0
- Bug fix
- There should not be any change in font case
> AST-2959 - Single post title transformed to capitalize after 4.0 update.

- changelog.txt
- inc/dynamic-css/block-editor-compatibility.php
- Earlier we had fixed Spectra blocks custom margin not applying with Astra Container Layouts:
https://brainstormforce.atlassian.net/browse/AST-2532
- However, the fix affects the starter template blocks alignments on the frontend which will affect the user experience, hence reverting some of the affecting css to avoid UAGB blocks mislignment issues for Starter Templates.
- https://brainstormforce.atlassian.net/browse/AST-3011
https://d.pr/i/loZ7IU
Fix: Some starter template gets shrink after importing
- Import any starter template.
- The blocks should not shrink.
> AST-3011 - Some starter template gets shrink after importing

- inc/builder/type/header/mobile-trigger/dynamic-css/dynamic.css.php
- Toggle: border radius is not working on frontend for tablet
- https://d.pr/i/EyhXu0
- Bug fix
- Header builder - Toggle
- Select outline style for toggle
- Assign border radius for all devices 
- Check the result on the frontend
> AST-3015 - Toggle button radius not working for tablet

- changelog.txt
- header.php
- Introduced new filter to remove gmpg link from link profile
- GitHub reported issue - https://github.com/brainstormforce/astra/issues/4172
- Without filter (normal webpage) - https://share.getcloudapp.com/5zuj7gA1
- With disabling filter - https://share.getcloudapp.com/eDurYW8P
```
add_filter( 'astra_header_profile_gmpg_link', '__return_false' );
```
- With this filter the link tag should disappear
> AST-2720 - Introduced new filter to remove gmpg link from link profile

- admin/includes/class-astra-menu.php
- tests/php/static-analysis-stubs/astra-stubs.php
- Updated the Spectra admin link from Astra dashboard as per the 2.4.1 Spectra release
- https://share.getcloudapp.com/L1uDdXDX
- New feature (non-breaking change)
- Test with master version (< 2.4.1)
- Test with 2.4.1 version
> AST-3106 - Updated Spectra admin page link as per the plugin v2.4.1 improvement

- changelog.txt
- inc/class-astra-dynamic-css.php
- https://wordpress.org/support/topic/debug-error-in-astra-4-1-0/
- In the responsive button CSS this issue happens
- Bug fix
- Add a button in the customizer header builder & check on the frontend
- Or simply use this customizer exported JSON - https://share.getcloudapp.com/8LuqbgAK
- Check responsive button global stylings (example- padding, margin) applying on respective responsive devices
> AST-3107 - Array to string conversion PHP notice due to button responsive parsing CSS

- changelog.txt
- inc/modules/related-posts/css/dynamic-css.php
**Description** - 
The Related Post Title Font Size does not work in the responsive mode. It seems to be working in the customizer but nothing happens on the front end.
**How to reproduce:**
Enable the related posts
From the design tab, try changing the related posts title font for mobile/tablet devices.
Changes are reflected in the customizer
Publish the changes and check the frontend. Font size is not changed on the front.
**Refer to the screencast:** 
https://d.pr/v/RVvCwK
> AST-3079 - fix: Related post title font size not working in mobile & tablet.

- changelog.txt
- inc/markup-extras.php
**Test Data: (If any)**  
Conflict with bbpress plugin in topic tags.
1. Install Astra and Bbpress
2. Create a new topic tag.
3. Check the topic tag page on frontend, it’s goes in infinite loop.
**Screencast** - https://d.pr/v/vbaKLn 
Any Other details:
> AST-3129 - Fix: Conflict with bbpress plugin in topic tags.

- changelog.txt
- inc/compatibility/woocommerce/class-astra-woocommerce.php
**Test Data: (If any)**  
When we add any multiple element widget which need a dropdown arrow like category with dropdown arrow so this arrow goes to top right corner which looks not good, need to be center like previous.
1. Install Astra then install any starter template 
2. Check on the any widget which is already added in sidebar
3. Dropdown arrow is showing in top right corner.
**Screenshot** - https://d.pr/i/YASDBo 
Any Other details:
> AST-3131 - Fix: Widget's dropdown arrow is moving to top corner.

- changelog.txt
- inc/customizer/class-astra-builder-customizer.php
- Description: Off canvas widget section is overlapping on customizer
- Existing compatibility added previously during 6.0 compatibility breaks with following css added:
`translateX(-57px) translateY(-208px) translateY(0em) scale(1) translateZ(0px) `
- Updating the z-index does not solve the problem, as the stack context is different which does not have any effect to solve the overlap issue.
- Screenshot: [Annotation-Annotation on 2023-04-04 at 14-26-05.png.png](https://d.pr/i/2af2eF)
- JIRA - https://brainstormforce.atlassian.net/browse/AST-3127
- Bug Screenshot: [Annotation-Annotation on 2023-04-04 at 14-26-05.png.png](https://d.pr/i/2af2eF)
- Before 6.1 - https://d.pr/i/SXi5mW
- Adjust position of popup to avoid overlap.
- Bug introduced with WordPress 6.1, popup positioning uses …
> AST-3127 - Popup menu overlaps customizer controls section.

- admin/includes/class-astra-menu.php
- Given that Spectra has brought up the top-level menu, we need to hide the Spectra menu conditionally when Spectra is installed. This would prevent the menu from being redundant.
- https://share.getcloudapp.com/bLulBz5v
- Compatibility (non-breaking change)
- Check with Spectra plugin
- - active state
- - inactive state
- not installed case
- installed but inactive case
- installed & active case
> AST-3113 - Removed spectra submenu from astra when top level spectra plugin menu activates

- changelog.txt
- inc/class-astra-dynamic-css.php
**Test Data: (If any)**  
We are getting some Fatal error: Uncaught TypeError: Unsupported operand types: On frontend and customizer .
**Screenshot** - https://d.pr/i/IURQeh 
Just import this customizer JSON file and you will noticed the error.
> AST-3211 - Fix: Fatal error: Uncaught TypeError: Unsupported operand types: On frontend and customizer.

- .github/workflows/pull-request-title.yml
- inc/customizer/configurations/layout/class-astra-blog-layout-configs.php
Removed extra Read time option from theme which visible even after addon is disable.
1. Keep only the Astra theme active
2. Navigate to Customize > Blog > Blog/Archive and enable the read time.
3. It does not have any effect.
4. If Astra Pro is activated with Blog Pro, then it has an effect and correctly appears.
- https://d.pr/v/9pNVsk
> AST-3269 - Fix: Removed extra Read time option from theme which visible even after addon is disable.

- changelog.txt
- inc/markup-extras.php
- Site title comes with h1 tag on home page & front page.
- https://d.pr/v/lFP6dV
- Bug fix 
- **Steps To Reproduce:** 
- 1. Enable site-title from the customizer
- 2. Check on the site frontend
- 3. Notice on home page & front page the h1 tag for site-title - [Astra 2023-08-01 at 11.04.44 AM](https://share.getcloudapp.com/8LuYly5p)  
- 4. Notice on other normal pages/posts there is span tag - [Shop – Astra 2023-08-01 at 11.05.53 AM](https://share.getcloudapp.com/6quJXkY1)
> AST-3375 - h1 tag assigned to site title on home & front page

- changelog.txt
- inc/compatibility/starter-content/home.php
> AST-3369 - For Astra theme preview page in editor button is not properly align 

- changelog.txt
- inc/assets/js/block-editor-script.js
- Titlevisibility meta option not working in Firefox browser.
- Bug - https://d.pr/i/Tq40IC
- Fix - https://d.pr/i/wao5LU
- Bug fix 
- As per test cases mentioned in the task
> AST-3434 - Title visibility meta option not working in Firefox browser

- changelog.txt
- inc/compatibility/class-astra-elementor.php
- Elementor Page by default should have Full-width layout selected.
- JIRA - https://brainstormforce.atlassian.net/browse/AST-3442
BugFixes
- Check if Full-width layout is applied properly same as before for Elementor Pages.
- Check for new user case.
- Check for old users migrating to latest version.
> AST-3442 - Fix - Update default layout to Page Builder when using Elementor

- changelog.txt
- inc/core/class-astra-wp-editor-css.php
- w.org reported issue - https://wordpress.org/support/topic/v4-3-0-breaks-global-color-settings-in-editor/
- Revert PR for this - https://github.com/brainstormforce/astra/pull/5287 
- [Markup 2023-09-04 at 10.53.46.png](https://d.pr/i/rFBzbh)  → [Markup 2023-09-04 at 10.54.12.png](https://d.pr/i/wheerL)
- Bug fix 
- As per the test cases mentioned in the task
> AST-3463 - Fix: Text color not inheriting in block editor

- changelog.txt
- inc/blog/blog-config.php
- "Read More" CTA does not appear with excerpt when left sidebar layout is active
Issue - https://d.pr/i/qbwBS3
Fix - https://d.pr/i/KTOGso
- Bug fix
- With free theme 
-  - With left-right-none sidebar layouts
- - Check with the other some archives like search/category archive/blog etc
- With pro addon
- - With left-right-none sidebar layouts
- - Check with+without the "Read More as Button" setting enabled
> AST-3456 - Blog Archive - Read More CTA not appearing when the Left Sidebar layout is active

- admin/assets/src/dashboard-app/pages/docs/Docs.js
- admin/assets/src/dashboard-app/pages/docs/UpgradeToPro.js
Fix: Added the text domain to two strings in UpgradeToPro.js and Docs.js
Fix: Added the text domain to two strings in UpgradeToPro.js
> Fix: Added the text domain to two strings in UpgradeToPro.js

- changelog.txt
- inc/markup-extras.php
- The Boxed Option for Container Style is not working for WooCommerce Cart & Checkout Pages.
- JIRA - https://brainstormforce.atlassian.net/browse/AST-3658
https://d.pr/i/tulLJ4
- WooCommerce Cart Page Meta Setting for Boxed should Override WooCommerce General Settings for Container Style.
- WooCommerce Checkout Page Meta Setting for Boxed should Override WooCommerce General Settings for Container Style.
> AST-3658 - Fix: WooCommerce - Boxed Style Option not working on WooCommerce Cart & Checkout Pages.

- inc/customizer/custom-controls/assets/js/unminified/custom-controls-plain.js
- inc/customizer/custom-controls/typography/selectWoo.css
- inc/customizer/custom-controls/typography/selectWoo.js
**Description**: In typography font family and font-weight dropdowns are not matching
**Current Behavior:**
- https://d.pr/i/35Lj0N 
**Expected Result:** 
- https://d.pr/i/mxZESl
- Minor Styling change - Non-breaking change.
- Test cases mention in the [task](https://brainstormforce.atlassian.net/browse/AST-3653)
> AST-3653 - Fix: Added old select2 dropdown arrow icon.

- inc/customizer/configurations/builder/header/configs/menu.php
- Menu section from customizer is not opening 
- Configurations got missed through looping
- https://d.pr/v/ATbbb5
- Bug fix 
- Check the menu section (exact fix)
- Check other element sections under header-footer builder
- Check some cloned element section (html / button / any)
> AST-3669 - Fix: menu section configurations missing under customizer

- inc/customizer/configurations/builder/footer/class-astra-customizer-footer-builder-configs.php
- inc/customizer/configurations/builder/footer/configs/footer-builder.php
- Fix: footer builder not opening under customizer
- https://d.pr/i/X5IlDG
- Bug fix
- Check footer builder panel (main bug)
- Check some other builder sections
> AST-3688 - Fix: footer builder panel missing in customizer

- changelog.txt
- inc/class-astra-dynamic-css.php
> AST-3607 - Fix:Border focus color not inherited correct input focus styling.

- changelog.txt
- inc/class-astra-after-setup-theme.php
- New product editor not working with the classic Astra theme, so restricting it as incompatibility.
- Bug fix
- Check the new product editor
> AST-3715 - Fix: Woo 8.4 compatibility with Astra

- changelog.txt
- inc/compatibility/woocommerce/class-astra-woocommerce.php
- Cart with "Hide Cart Total Label" throwing fatal error in editor with Starter Template
- https://d.pr/v/pZddub
- Bug fix 
- Test data added in the cart
> AST-3721 - fix: PHP fatal error 'Uncaught Error: Call to a member function get_cart_contents_total() on null'

- changelog.txt
- inc/customizer/configurations/builder/header/class-astra-customizer-woo-cart-configs.php
Site crashing issue for old header builders user due to recent update.
1. Switch to old header builder - Use filter - add_filter( 'astra_is_header_footer_builder_active', '__return_false' );
2. Make sure WooCommerce is Installed.
3. Check inside the customiser, you will see the error.
**Thread** - https://brainstormforce.slack.com/archives/CDS7TQ75Z/p1702471401993739
> AST-3728 - Fix: Site crashing issue for old header builder user due to recent update.
